// Code generated by solo-kit. DO NOT EDIT.

package v1alpha1

import (
	"fmt"
	"hash"
	"hash/fnv"
	"log"

	"github.com/rotisserie/eris"
	"github.com/solo-io/go-utils/hashutils"
	"go.uber.org/zap"
)

type EnterpriseSnapshot struct {
	GraphqlSchemas GraphQLExtendedSchemaList
}

func (s EnterpriseSnapshot) Clone() EnterpriseSnapshot {
	return EnterpriseSnapshot{
		GraphqlSchemas: s.GraphqlSchemas.Clone(),
	}
}

func (s EnterpriseSnapshot) Hash(hasher hash.Hash64) (uint64, error) {
	if hasher == nil {
		hasher = fnv.New64()
	}
	if _, err := s.hashGraphqlSchemas(hasher); err != nil {
		return 0, err
	}
	return hasher.Sum64(), nil
}

func (s EnterpriseSnapshot) hashGraphqlSchemas(hasher hash.Hash64) (uint64, error) {
	return hashutils.HashAllSafe(hasher, s.GraphqlSchemas.AsInterfaces()...)
}

func (s EnterpriseSnapshot) HashFields() []zap.Field {
	var fields []zap.Field
	hasher := fnv.New64()
	GraphqlSchemasHash, err := s.hashGraphqlSchemas(hasher)
	if err != nil {
		log.Println(eris.Wrapf(err, "error hashing, this should never happen"))
	}
	fields = append(fields, zap.Uint64("graphqlSchemas", GraphqlSchemasHash))
	snapshotHash, err := s.Hash(hasher)
	if err != nil {
		log.Println(eris.Wrapf(err, "error hashing, this should never happen"))
	}
	return append(fields, zap.Uint64("snapshotHash", snapshotHash))
}

type EnterpriseSnapshotStringer struct {
	Version        uint64
	GraphqlSchemas []string
}

func (ss EnterpriseSnapshotStringer) String() string {
	s := fmt.Sprintf("EnterpriseSnapshot %v\n", ss.Version)

	s += fmt.Sprintf("  GraphqlSchemas %v\n", len(ss.GraphqlSchemas))
	for _, name := range ss.GraphqlSchemas {
		s += fmt.Sprintf("    %v\n", name)
	}

	return s
}

func (s EnterpriseSnapshot) Stringer() EnterpriseSnapshotStringer {
	snapshotHash, err := s.Hash(nil)
	if err != nil {
		log.Println(eris.Wrapf(err, "error hashing, this should never happen"))
	}
	return EnterpriseSnapshotStringer{
		Version:        snapshotHash,
		GraphqlSchemas: s.GraphqlSchemas.NamespacesDotNames(),
	}
}
