// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// CorsPolicyApplyConfiguration represents a declarative configuration of the CorsPolicy type for use
// with apply.
type CorsPolicyApplyConfiguration struct {
	AllowOrigins     []string `json:"allowOrigins,omitempty"`
	AllowMethods     []string `json:"allowMethods,omitempty"`
	AllowHeaders     []string `json:"allowHeaders,omitempty"`
	AllowCredentials *bool    `json:"allowCredentials,omitempty"`
	ExposeHeaders    []string `json:"exposeHeaders,omitempty"`
	MaxAge           *string  `json:"maxAge,omitempty"`
}

// CorsPolicyApplyConfiguration constructs a declarative configuration of the CorsPolicy type for use with
// apply.
func CorsPolicy() *CorsPolicyApplyConfiguration {
	return &CorsPolicyApplyConfiguration{}
}

// WithAllowOrigins adds the given value to the AllowOrigins field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the AllowOrigins field.
func (b *CorsPolicyApplyConfiguration) WithAllowOrigins(values ...string) *CorsPolicyApplyConfiguration {
	for i := range values {
		b.AllowOrigins = append(b.AllowOrigins, values[i])
	}
	return b
}

// WithAllowMethods adds the given value to the AllowMethods field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the AllowMethods field.
func (b *CorsPolicyApplyConfiguration) WithAllowMethods(values ...string) *CorsPolicyApplyConfiguration {
	for i := range values {
		b.AllowMethods = append(b.AllowMethods, values[i])
	}
	return b
}

// WithAllowHeaders adds the given value to the AllowHeaders field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the AllowHeaders field.
func (b *CorsPolicyApplyConfiguration) WithAllowHeaders(values ...string) *CorsPolicyApplyConfiguration {
	for i := range values {
		b.AllowHeaders = append(b.AllowHeaders, values[i])
	}
	return b
}

// WithAllowCredentials sets the AllowCredentials field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AllowCredentials field is set to the value of the last call.
func (b *CorsPolicyApplyConfiguration) WithAllowCredentials(value bool) *CorsPolicyApplyConfiguration {
	b.AllowCredentials = &value
	return b
}

// WithExposeHeaders adds the given value to the ExposeHeaders field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the ExposeHeaders field.
func (b *CorsPolicyApplyConfiguration) WithExposeHeaders(values ...string) *CorsPolicyApplyConfiguration {
	for i := range values {
		b.ExposeHeaders = append(b.ExposeHeaders, values[i])
	}
	return b
}

// WithMaxAge sets the MaxAge field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MaxAge field is set to the value of the last call.
func (b *CorsPolicyApplyConfiguration) WithMaxAge(value string) *CorsPolicyApplyConfiguration {
	b.MaxAge = &value
	return b
}
