// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: github.com/solo-io/gloo/projects/gloo/api/v1/circuit_breaker.proto

package v1

import (
	bytes "bytes"
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	types "github.com/gogo/protobuf/types"
	_ "github.com/solo-io/protoc-gen-ext/extproto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// SslConfig contains the options necessary to configure a virtual host or listener to use TLS
// See the [envoy docs](https://www.envoyproxy.io/docs/envoy/latest/api-v2/api/v2/cluster/circuit_breaker.proto#envoy-api-msg-cluster-circuitbreakers)
// for the meaning of these values.
type CircuitBreakerConfig struct {
	MaxConnections       *types.UInt32Value `protobuf:"bytes,1,opt,name=max_connections,json=maxConnections,proto3" json:"max_connections,omitempty"`
	MaxPendingRequests   *types.UInt32Value `protobuf:"bytes,2,opt,name=max_pending_requests,json=maxPendingRequests,proto3" json:"max_pending_requests,omitempty"`
	MaxRequests          *types.UInt32Value `protobuf:"bytes,3,opt,name=max_requests,json=maxRequests,proto3" json:"max_requests,omitempty"`
	MaxRetries           *types.UInt32Value `protobuf:"bytes,4,opt,name=max_retries,json=maxRetries,proto3" json:"max_retries,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *CircuitBreakerConfig) Reset()         { *m = CircuitBreakerConfig{} }
func (m *CircuitBreakerConfig) String() string { return proto.CompactTextString(m) }
func (*CircuitBreakerConfig) ProtoMessage()    {}
func (*CircuitBreakerConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_358fe1fcb8924174, []int{0}
}
func (m *CircuitBreakerConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CircuitBreakerConfig.Unmarshal(m, b)
}
func (m *CircuitBreakerConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CircuitBreakerConfig.Marshal(b, m, deterministic)
}
func (m *CircuitBreakerConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CircuitBreakerConfig.Merge(m, src)
}
func (m *CircuitBreakerConfig) XXX_Size() int {
	return xxx_messageInfo_CircuitBreakerConfig.Size(m)
}
func (m *CircuitBreakerConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_CircuitBreakerConfig.DiscardUnknown(m)
}

var xxx_messageInfo_CircuitBreakerConfig proto.InternalMessageInfo

func (m *CircuitBreakerConfig) GetMaxConnections() *types.UInt32Value {
	if m != nil {
		return m.MaxConnections
	}
	return nil
}

func (m *CircuitBreakerConfig) GetMaxPendingRequests() *types.UInt32Value {
	if m != nil {
		return m.MaxPendingRequests
	}
	return nil
}

func (m *CircuitBreakerConfig) GetMaxRequests() *types.UInt32Value {
	if m != nil {
		return m.MaxRequests
	}
	return nil
}

func (m *CircuitBreakerConfig) GetMaxRetries() *types.UInt32Value {
	if m != nil {
		return m.MaxRetries
	}
	return nil
}

func init() {
	proto.RegisterType((*CircuitBreakerConfig)(nil), "gloo.solo.io.CircuitBreakerConfig")
}

func init() {
	proto.RegisterFile("github.com/solo-io/gloo/projects/gloo/api/v1/circuit_breaker.proto", fileDescriptor_358fe1fcb8924174)
}

var fileDescriptor_358fe1fcb8924174 = []byte{
	// 300 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x91, 0x31, 0x4f, 0xf3, 0x30,
	0x10, 0x86, 0x95, 0x7e, 0x9f, 0x18, 0xdc, 0x0a, 0x24, 0xab, 0x43, 0x55, 0xa1, 0x0a, 0x31, 0xb1,
	0x60, 0x43, 0x3b, 0x31, 0x20, 0xa4, 0x54, 0x0c, 0x2c, 0x08, 0x55, 0x82, 0x81, 0xa5, 0x72, 0xcc,
	0xd5, 0x98, 0x26, 0x3e, 0x63, 0x3b, 0xe0, 0x9f, 0xc4, 0xc2, 0x9f, 0xe2, 0x57, 0x30, 0xa2, 0xc4,
	0xa1, 0xac, 0xd9, 0x7c, 0xbe, 0xf7, 0x79, 0xde, 0xe1, 0x48, 0xae, 0x74, 0x78, 0xae, 0x0b, 0x26,
	0xb1, 0xe2, 0x1e, 0x4b, 0x3c, 0xd5, 0xc8, 0x55, 0x89, 0xc8, 0xad, 0xc3, 0x17, 0x90, 0xc1, 0xa7,
	0x49, 0x58, 0xcd, 0xdf, 0xce, 0xb9, 0xd4, 0x4e, 0xd6, 0x3a, 0xac, 0x0b, 0x07, 0x62, 0x0b, 0x8e,
	0x59, 0x87, 0x01, 0xe9, 0xa8, 0x89, 0xb0, 0x86, 0x66, 0x1a, 0xa7, 0x63, 0x85, 0x0a, 0xdb, 0x05,
	0x6f, 0x5e, 0x29, 0x33, 0x9d, 0x29, 0x44, 0x55, 0x02, 0x6f, 0xa7, 0xa2, 0xde, 0xf0, 0x77, 0x27,
	0xac, 0x05, 0xe7, 0xbb, 0x3d, 0x85, 0x18, 0x12, 0x04, 0x31, 0xa4, 0xbf, 0xe3, 0xcf, 0x01, 0x19,
	0x2f, 0x53, 0x63, 0x9e, 0x0a, 0x97, 0x68, 0x36, 0x5a, 0xd1, 0x6b, 0x72, 0x50, 0x89, 0xb8, 0x96,
	0x68, 0x0c, 0xc8, 0xa0, 0xd1, 0xf8, 0x49, 0x76, 0x94, 0x9d, 0x0c, 0xe7, 0x87, 0x2c, 0xd5, 0xb0,
	0xdf, 0x1a, 0x76, 0x7f, 0x63, 0xc2, 0x62, 0xfe, 0x20, 0xca, 0x1a, 0x56, 0xfb, 0x95, 0x88, 0xcb,
	0x3f, 0x86, 0xde, 0x92, 0x71, 0xa3, 0xb1, 0x60, 0x9e, 0xb4, 0x51, 0x6b, 0x07, 0xaf, 0x35, 0xf8,
	0xe0, 0x27, 0x83, 0x1e, 0x2e, 0x5a, 0x89, 0x78, 0x97, 0xc0, 0x55, 0xc7, 0xd1, 0x2b, 0x32, 0x6a,
	0x7c, 0x3b, 0xcf, 0xbf, 0x1e, 0x9e, 0x61, 0x25, 0xe2, 0x4e, 0x70, 0x49, 0x86, 0x49, 0x10, 0x9c,
	0x06, 0x3f, 0xf9, 0xdf, 0x83, 0x27, 0x2d, 0xdf, 0xe6, 0xf3, 0x8b, 0xef, 0x3c, 0xfb, 0xf8, 0x9a,
	0x65, 0x8f, 0x67, 0xfd, 0x8e, 0x6a, 0xb7, 0xaa, 0x3b, 0x6c, 0xb1, 0xd7, 0xca, 0x17, 0x3f, 0x01,
	0x00, 0x00, 0xff, 0xff, 0xc8, 0x10, 0x42, 0x1e, 0x0f, 0x02, 0x00, 0x00,
}

func (this *CircuitBreakerConfig) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*CircuitBreakerConfig)
	if !ok {
		that2, ok := that.(CircuitBreakerConfig)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.MaxConnections.Equal(that1.MaxConnections) {
		return false
	}
	if !this.MaxPendingRequests.Equal(that1.MaxPendingRequests) {
		return false
	}
	if !this.MaxRequests.Equal(that1.MaxRequests) {
		return false
	}
	if !this.MaxRetries.Equal(that1.MaxRetries) {
		return false
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}
