// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: github.com/solo-io/gloo/projects/gloo/api/v1/plugins.proto

package v1

import (
	bytes "bytes"
	fmt "fmt"
	math "math"
	time "time"

	cluster "github.com/envoyproxy/go-control-plane/envoy/api/v2/cluster"
	core "github.com/envoyproxy/go-control-plane/envoy/api/v2/core"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	_ "github.com/gogo/protobuf/types"
	_ "github.com/solo-io/gloo/projects/gloo/pkg/api/v1/enterprise/plugins/extauth"
	_ "github.com/solo-io/gloo/projects/gloo/pkg/api/v1/enterprise/plugins/jwt"
	ratelimit "github.com/solo-io/gloo/projects/gloo/pkg/api/v1/enterprise/plugins/ratelimit"
	_ "github.com/solo-io/gloo/projects/gloo/pkg/api/v1/enterprise/plugins/rbac"
	waf "github.com/solo-io/gloo/projects/gloo/pkg/api/v1/enterprise/plugins/waf"
	als "github.com/solo-io/gloo/projects/gloo/pkg/api/v1/plugins/als"
	aws "github.com/solo-io/gloo/projects/gloo/pkg/api/v1/plugins/aws"
	ec2 "github.com/solo-io/gloo/projects/gloo/pkg/api/v1/plugins/aws/ec2"
	azure "github.com/solo-io/gloo/projects/gloo/pkg/api/v1/plugins/azure"
	consul "github.com/solo-io/gloo/projects/gloo/pkg/api/v1/plugins/consul"
	cors "github.com/solo-io/gloo/projects/gloo/pkg/api/v1/plugins/cors"
	faultinjection "github.com/solo-io/gloo/projects/gloo/pkg/api/v1/plugins/faultinjection"
	grpc "github.com/solo-io/gloo/projects/gloo/pkg/api/v1/plugins/grpc"
	grpc_web "github.com/solo-io/gloo/projects/gloo/pkg/api/v1/plugins/grpc_web"
	hcm "github.com/solo-io/gloo/projects/gloo/pkg/api/v1/plugins/hcm"
	headers "github.com/solo-io/gloo/projects/gloo/pkg/api/v1/plugins/headers"
	healthcheck "github.com/solo-io/gloo/projects/gloo/pkg/api/v1/plugins/healthcheck"
	hostrewrite "github.com/solo-io/gloo/projects/gloo/pkg/api/v1/plugins/hostrewrite"
	kubernetes "github.com/solo-io/gloo/projects/gloo/pkg/api/v1/plugins/kubernetes"
	lbhash "github.com/solo-io/gloo/projects/gloo/pkg/api/v1/plugins/lbhash"
	pipe "github.com/solo-io/gloo/projects/gloo/pkg/api/v1/plugins/pipe"
	rest "github.com/solo-io/gloo/projects/gloo/pkg/api/v1/plugins/rest"
	retries "github.com/solo-io/gloo/projects/gloo/pkg/api/v1/plugins/retries"
	shadowing "github.com/solo-io/gloo/projects/gloo/pkg/api/v1/plugins/shadowing"
	static "github.com/solo-io/gloo/projects/gloo/pkg/api/v1/plugins/static"
	stats "github.com/solo-io/gloo/projects/gloo/pkg/api/v1/plugins/stats"
	tcp "github.com/solo-io/gloo/projects/gloo/pkg/api/v1/plugins/tcp"
	tracing "github.com/solo-io/gloo/projects/gloo/pkg/api/v1/plugins/tracing"
	transformation "github.com/solo-io/gloo/projects/gloo/pkg/api/v1/plugins/transformation"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Plugin-specific configuration that lives on gateways
// Each ListenerPlugin object contains configuration for a specific plugin
// Note to developers: new Listener Plugins must be added to this struct
// to be usable by Gloo.
type ListenerPlugins struct {
	AccessLoggingService *als.AccessLoggingService `protobuf:"bytes,1,opt,name=access_logging_service,json=accessLoggingService,proto3" json:"access_logging_service,omitempty"`
	// Deprecated: Opaque config for Gloo plugins
	Extensions           *Extensions `protobuf:"bytes,2,opt,name=extensions,proto3" json:"extensions,omitempty"` // Deprecated: Do not use.
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ListenerPlugins) Reset()         { *m = ListenerPlugins{} }
func (m *ListenerPlugins) String() string { return proto.CompactTextString(m) }
func (*ListenerPlugins) ProtoMessage()    {}
func (*ListenerPlugins) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae47d2df5fad2a45, []int{0}
}
func (m *ListenerPlugins) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListenerPlugins.Unmarshal(m, b)
}
func (m *ListenerPlugins) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListenerPlugins.Marshal(b, m, deterministic)
}
func (m *ListenerPlugins) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListenerPlugins.Merge(m, src)
}
func (m *ListenerPlugins) XXX_Size() int {
	return xxx_messageInfo_ListenerPlugins.Size(m)
}
func (m *ListenerPlugins) XXX_DiscardUnknown() {
	xxx_messageInfo_ListenerPlugins.DiscardUnknown(m)
}

var xxx_messageInfo_ListenerPlugins proto.InternalMessageInfo

func (m *ListenerPlugins) GetAccessLoggingService() *als.AccessLoggingService {
	if m != nil {
		return m.AccessLoggingService
	}
	return nil
}

// Deprecated: Do not use.
func (m *ListenerPlugins) GetExtensions() *Extensions {
	if m != nil {
		return m.Extensions
	}
	return nil
}

// Plugin-specific configuration that lives on http listeners
type HttpListenerPlugins struct {
	GrpcWeb                       *grpc_web.GrpcWeb                  `protobuf:"bytes,1,opt,name=grpc_web,json=grpcWeb,proto3" json:"grpc_web,omitempty"`
	HttpConnectionManagerSettings *hcm.HttpConnectionManagerSettings `protobuf:"bytes,2,opt,name=http_connection_manager_settings,json=httpConnectionManagerSettings,proto3" json:"http_connection_manager_settings,omitempty"`
	// enable [Envoy health checks](https://www.envoyproxy.io/docs/envoy/v1.7.0/api-v2/config/filter/http/health_check/v2/health_check.proto) on this listener
	HealthCheck *healthcheck.HealthCheck `protobuf:"bytes,4,opt,name=health_check,json=healthCheck,proto3" json:"health_check,omitempty"`
	// Deprecated: Opaque config for Gloo plugins
	Extensions *Extensions `protobuf:"bytes,3,opt,name=extensions,proto3" json:"extensions,omitempty"` // Deprecated: Do not use.
	// Enterprise-only: Config for Web Application Firewall (WAF), supporting
	// the popular ModSecurity 3.0.3 ruleset
	Waf                  *waf.Settings `protobuf:"bytes,5,opt,name=waf,proto3" json:"waf,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *HttpListenerPlugins) Reset()         { *m = HttpListenerPlugins{} }
func (m *HttpListenerPlugins) String() string { return proto.CompactTextString(m) }
func (*HttpListenerPlugins) ProtoMessage()    {}
func (*HttpListenerPlugins) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae47d2df5fad2a45, []int{1}
}
func (m *HttpListenerPlugins) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HttpListenerPlugins.Unmarshal(m, b)
}
func (m *HttpListenerPlugins) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HttpListenerPlugins.Marshal(b, m, deterministic)
}
func (m *HttpListenerPlugins) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HttpListenerPlugins.Merge(m, src)
}
func (m *HttpListenerPlugins) XXX_Size() int {
	return xxx_messageInfo_HttpListenerPlugins.Size(m)
}
func (m *HttpListenerPlugins) XXX_DiscardUnknown() {
	xxx_messageInfo_HttpListenerPlugins.DiscardUnknown(m)
}

var xxx_messageInfo_HttpListenerPlugins proto.InternalMessageInfo

func (m *HttpListenerPlugins) GetGrpcWeb() *grpc_web.GrpcWeb {
	if m != nil {
		return m.GrpcWeb
	}
	return nil
}

func (m *HttpListenerPlugins) GetHttpConnectionManagerSettings() *hcm.HttpConnectionManagerSettings {
	if m != nil {
		return m.HttpConnectionManagerSettings
	}
	return nil
}

func (m *HttpListenerPlugins) GetHealthCheck() *healthcheck.HealthCheck {
	if m != nil {
		return m.HealthCheck
	}
	return nil
}

// Deprecated: Do not use.
func (m *HttpListenerPlugins) GetExtensions() *Extensions {
	if m != nil {
		return m.Extensions
	}
	return nil
}

func (m *HttpListenerPlugins) GetWaf() *waf.Settings {
	if m != nil {
		return m.Waf
	}
	return nil
}

// Plugin-specific configuration that lives on tcp listeners
type TcpListenerPlugins struct {
	TcpProxySettings     *tcp.TcpProxySettings `protobuf:"bytes,3,opt,name=tcp_proxy_settings,json=tcpProxySettings,proto3" json:"tcp_proxy_settings,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *TcpListenerPlugins) Reset()         { *m = TcpListenerPlugins{} }
func (m *TcpListenerPlugins) String() string { return proto.CompactTextString(m) }
func (*TcpListenerPlugins) ProtoMessage()    {}
func (*TcpListenerPlugins) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae47d2df5fad2a45, []int{2}
}
func (m *TcpListenerPlugins) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TcpListenerPlugins.Unmarshal(m, b)
}
func (m *TcpListenerPlugins) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TcpListenerPlugins.Marshal(b, m, deterministic)
}
func (m *TcpListenerPlugins) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TcpListenerPlugins.Merge(m, src)
}
func (m *TcpListenerPlugins) XXX_Size() int {
	return xxx_messageInfo_TcpListenerPlugins.Size(m)
}
func (m *TcpListenerPlugins) XXX_DiscardUnknown() {
	xxx_messageInfo_TcpListenerPlugins.DiscardUnknown(m)
}

var xxx_messageInfo_TcpListenerPlugins proto.InternalMessageInfo

func (m *TcpListenerPlugins) GetTcpProxySettings() *tcp.TcpProxySettings {
	if m != nil {
		return m.TcpProxySettings
	}
	return nil
}

// Plugin-specific configuration that lives on virtual hosts
// Each VirtualHostPlugin object contains configuration for a specific plugin
// Note to developers: new Virtual Host Plugins must be added to this struct
// to be usable by Gloo.
type VirtualHostPlugins struct {
	// Deprecated: Opaque config for Gloo plugins
	Extensions *Extensions          `protobuf:"bytes,1,opt,name=extensions,proto3" json:"extensions,omitempty"` // Deprecated: Do not use.
	Retries    *retries.RetryPolicy `protobuf:"bytes,5,opt,name=retries,proto3" json:"retries,omitempty"`
	Stats      *stats.Stats         `protobuf:"bytes,10,opt,name=stats,proto3" json:"stats,omitempty"`
	// Append/Remove headers on Requests or Responses on all routes contained in this Virtual Host
	HeaderManipulation *headers.HeaderManipulation `protobuf:"bytes,2,opt,name=header_manipulation,json=headerManipulation,proto3" json:"header_manipulation,omitempty"`
	// Defines a CORS policy for the virtual host
	// If a CORS policy is also defined on the route matched by the request, the policies are merged.
	Cors *cors.CorsPolicy `protobuf:"bytes,3,opt,name=cors,proto3" json:"cors,omitempty"`
	// Transformations to apply
	Transformations *transformation.RouteTransformations `protobuf:"bytes,4,opt,name=transformations,proto3" json:"transformations,omitempty"`
	// Enterprise-only: Config for GlooE rate-limiting using simplified (gloo-specific) API
	RatelimitGloo *ratelimit.IngressRateLimit `protobuf:"bytes,6,opt,name=ratelimit_gloo,json=ratelimitGloo,proto3" json:"ratelimit_gloo,omitempty"`
	// Enterprise-only: Partial config for GlooE rate-limiting based on Envoy's rate-limit service;
	// supports Envoy's rate-limit service API. (reference here: https://github.com/lyft/ratelimit#configuration)
	// Configure rate-limit *actions* here, which define how request characteristics get translated into
	// descriptors used by the rate-limit service for rate-limiting. Configure rate-limit *descriptors* and
	// their associated limits on the Gloo settings
	RatelimitActions *ratelimit.RateLimitVhostExtension `protobuf:"bytes,7,opt,name=ratelimit_actions,json=ratelimitActions,proto3" json:"ratelimit_actions,omitempty"`
	// Enterprise-only: Config for Web Application Firewall (WAF), supporting
	// the popular ModSecurity 3.0.3 ruleset
	Waf                  *waf.VhostSettings `protobuf:"bytes,8,opt,name=waf,proto3" json:"waf,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *VirtualHostPlugins) Reset()         { *m = VirtualHostPlugins{} }
func (m *VirtualHostPlugins) String() string { return proto.CompactTextString(m) }
func (*VirtualHostPlugins) ProtoMessage()    {}
func (*VirtualHostPlugins) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae47d2df5fad2a45, []int{3}
}
func (m *VirtualHostPlugins) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VirtualHostPlugins.Unmarshal(m, b)
}
func (m *VirtualHostPlugins) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VirtualHostPlugins.Marshal(b, m, deterministic)
}
func (m *VirtualHostPlugins) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VirtualHostPlugins.Merge(m, src)
}
func (m *VirtualHostPlugins) XXX_Size() int {
	return xxx_messageInfo_VirtualHostPlugins.Size(m)
}
func (m *VirtualHostPlugins) XXX_DiscardUnknown() {
	xxx_messageInfo_VirtualHostPlugins.DiscardUnknown(m)
}

var xxx_messageInfo_VirtualHostPlugins proto.InternalMessageInfo

// Deprecated: Do not use.
func (m *VirtualHostPlugins) GetExtensions() *Extensions {
	if m != nil {
		return m.Extensions
	}
	return nil
}

func (m *VirtualHostPlugins) GetRetries() *retries.RetryPolicy {
	if m != nil {
		return m.Retries
	}
	return nil
}

func (m *VirtualHostPlugins) GetStats() *stats.Stats {
	if m != nil {
		return m.Stats
	}
	return nil
}

func (m *VirtualHostPlugins) GetHeaderManipulation() *headers.HeaderManipulation {
	if m != nil {
		return m.HeaderManipulation
	}
	return nil
}

func (m *VirtualHostPlugins) GetCors() *cors.CorsPolicy {
	if m != nil {
		return m.Cors
	}
	return nil
}

func (m *VirtualHostPlugins) GetTransformations() *transformation.RouteTransformations {
	if m != nil {
		return m.Transformations
	}
	return nil
}

func (m *VirtualHostPlugins) GetRatelimitGloo() *ratelimit.IngressRateLimit {
	if m != nil {
		return m.RatelimitGloo
	}
	return nil
}

func (m *VirtualHostPlugins) GetRatelimitActions() *ratelimit.RateLimitVhostExtension {
	if m != nil {
		return m.RatelimitActions
	}
	return nil
}

func (m *VirtualHostPlugins) GetWaf() *waf.VhostSettings {
	if m != nil {
		return m.Waf
	}
	return nil
}

// Plugin-specific configuration that lives on routes
// Each RoutePlugin object contains configuration for a specific plugin
// Note to developers: new Route Plugins must be added to this struct
// to be usable by Gloo.
type RoutePlugins struct {
	// Transformations to apply
	Transformations *transformation.RouteTransformations `protobuf:"bytes,1,opt,name=transformations,proto3" json:"transformations,omitempty"`
	Faults          *faultinjection.RouteFaults          `protobuf:"bytes,2,opt,name=faults,proto3" json:"faults,omitempty"`
	PrefixRewrite   *transformation.PrefixRewrite        `protobuf:"bytes,3,opt,name=prefix_rewrite,json=prefixRewrite,proto3" json:"prefix_rewrite,omitempty"`
	Timeout         *time.Duration                       `protobuf:"bytes,4,opt,name=timeout,proto3,stdduration" json:"timeout,omitempty"`
	Retries         *retries.RetryPolicy                 `protobuf:"bytes,5,opt,name=retries,proto3" json:"retries,omitempty"`
	// Deprecated: Opaque config for Gloo plugins
	Extensions *Extensions `protobuf:"bytes,6,opt,name=extensions,proto3" json:"extensions,omitempty"` // Deprecated: Do not use.
	// Defines route-specific tracing configuration.
	// See here for additional information on Envoy's tracing capabilities: https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/observability/tracing.html
	// See here for additional information about configuring tracing with Gloo: https://gloo.solo.io/user_guides/setup_options/observability/#tracing
	Tracing *tracing.RouteTracingSettings `protobuf:"bytes,7,opt,name=tracing,proto3" json:"tracing,omitempty"`
	// Specifies traffic shadowing configuration for the route.
	// See here for additional information on Envoy's shadowing capabilities: https://www.envoyproxy.io/docs/envoy/latest/api-v2/api/v2/route/route.proto#envoy-api-msg-route-routeaction-requestmirrorpolicy
	Shadowing *shadowing.RouteShadowing `protobuf:"bytes,8,opt,name=shadowing,proto3" json:"shadowing,omitempty"`
	// Append/Remove headers on Requests or Responses on this Route
	HeaderManipulation *headers.HeaderManipulation `protobuf:"bytes,9,opt,name=header_manipulation,json=headerManipulation,proto3" json:"header_manipulation,omitempty"`
	// Rewrite the Host header for requests matched on this route
	HostRewrite *hostrewrite.HostRewrite `protobuf:"bytes,10,opt,name=host_rewrite,json=hostRewrite,proto3" json:"host_rewrite,omitempty"`
	// Defines a CORS policy for the route
	// If a CORS policy is also defined on the route's virtual host, the policies are merged.
	Cors *cors.CorsPolicy `protobuf:"bytes,11,opt,name=cors,proto3" json:"cors,omitempty"`
	// For routes served by a hashing load balancer, this defines the input to the hash key
	// Gloo configures Envoy with the first available RouteActionHashConfig among the following ordered list of providers:
	// - route, upstream, virtual service
	LbHash *lbhash.RouteActionHashConfig `protobuf:"bytes,12,opt,name=lb_hash,json=lbHash,proto3" json:"lb_hash,omitempty"`
	// Enterprise-only: Config for GlooE rate-limiting using simplified (gloo-specific) API
	RatelimitGloo *ratelimit.IngressRateLimit `protobuf:"bytes,13,opt,name=ratelimit_gloo,json=ratelimitGloo,proto3" json:"ratelimit_gloo,omitempty"`
	// Enterprise-only: Partial config for GlooE rate-limiting based on Envoy's rate-limit service;
	// supports Envoy's rate-limit service API. (reference here: https://github.com/lyft/ratelimit#configuration)
	// Configure rate-limit *actions* here, which define how request characteristics get translated into
	// descriptors used by the rate-limit service for rate-limiting. Configure rate-limit *descriptors* and
	// their associated limits on the Gloo settings
	RatelimitActions *ratelimit.RateLimitRouteExtension `protobuf:"bytes,14,opt,name=ratelimit_actions,json=ratelimitActions,proto3" json:"ratelimit_actions,omitempty"`
	// Enterprise-only: Config for Web Application Firewall (WAF), supporting
	// the popular ModSecurity 3.0.3 ruleset
	Waf                  *waf.RouteSettings `protobuf:"bytes,15,opt,name=waf,proto3" json:"waf,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *RoutePlugins) Reset()         { *m = RoutePlugins{} }
func (m *RoutePlugins) String() string { return proto.CompactTextString(m) }
func (*RoutePlugins) ProtoMessage()    {}
func (*RoutePlugins) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae47d2df5fad2a45, []int{4}
}
func (m *RoutePlugins) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoutePlugins.Unmarshal(m, b)
}
func (m *RoutePlugins) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoutePlugins.Marshal(b, m, deterministic)
}
func (m *RoutePlugins) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoutePlugins.Merge(m, src)
}
func (m *RoutePlugins) XXX_Size() int {
	return xxx_messageInfo_RoutePlugins.Size(m)
}
func (m *RoutePlugins) XXX_DiscardUnknown() {
	xxx_messageInfo_RoutePlugins.DiscardUnknown(m)
}

var xxx_messageInfo_RoutePlugins proto.InternalMessageInfo

func (m *RoutePlugins) GetTransformations() *transformation.RouteTransformations {
	if m != nil {
		return m.Transformations
	}
	return nil
}

func (m *RoutePlugins) GetFaults() *faultinjection.RouteFaults {
	if m != nil {
		return m.Faults
	}
	return nil
}

func (m *RoutePlugins) GetPrefixRewrite() *transformation.PrefixRewrite {
	if m != nil {
		return m.PrefixRewrite
	}
	return nil
}

func (m *RoutePlugins) GetTimeout() *time.Duration {
	if m != nil {
		return m.Timeout
	}
	return nil
}

func (m *RoutePlugins) GetRetries() *retries.RetryPolicy {
	if m != nil {
		return m.Retries
	}
	return nil
}

// Deprecated: Do not use.
func (m *RoutePlugins) GetExtensions() *Extensions {
	if m != nil {
		return m.Extensions
	}
	return nil
}

func (m *RoutePlugins) GetTracing() *tracing.RouteTracingSettings {
	if m != nil {
		return m.Tracing
	}
	return nil
}

func (m *RoutePlugins) GetShadowing() *shadowing.RouteShadowing {
	if m != nil {
		return m.Shadowing
	}
	return nil
}

func (m *RoutePlugins) GetHeaderManipulation() *headers.HeaderManipulation {
	if m != nil {
		return m.HeaderManipulation
	}
	return nil
}

func (m *RoutePlugins) GetHostRewrite() *hostrewrite.HostRewrite {
	if m != nil {
		return m.HostRewrite
	}
	return nil
}

func (m *RoutePlugins) GetCors() *cors.CorsPolicy {
	if m != nil {
		return m.Cors
	}
	return nil
}

func (m *RoutePlugins) GetLbHash() *lbhash.RouteActionHashConfig {
	if m != nil {
		return m.LbHash
	}
	return nil
}

func (m *RoutePlugins) GetRatelimitGloo() *ratelimit.IngressRateLimit {
	if m != nil {
		return m.RatelimitGloo
	}
	return nil
}

func (m *RoutePlugins) GetRatelimitActions() *ratelimit.RateLimitRouteExtension {
	if m != nil {
		return m.RatelimitActions
	}
	return nil
}

func (m *RoutePlugins) GetWaf() *waf.RouteSettings {
	if m != nil {
		return m.Waf
	}
	return nil
}

// Configuration for Destinations that are tied to the UpstreamSpec or ServiceSpec on that destination
type DestinationSpec struct {
	// Note to developers: new DestinationSpecs must be added to this oneof field
	// to be usable by Gloo.
	//
	// Types that are valid to be assigned to DestinationType:
	//	*DestinationSpec_Aws
	//	*DestinationSpec_Azure
	//	*DestinationSpec_Rest
	//	*DestinationSpec_Grpc
	DestinationType      isDestinationSpec_DestinationType `protobuf_oneof:"destination_type"`
	XXX_NoUnkeyedLiteral struct{}                          `json:"-"`
	XXX_unrecognized     []byte                            `json:"-"`
	XXX_sizecache        int32                             `json:"-"`
}

func (m *DestinationSpec) Reset()         { *m = DestinationSpec{} }
func (m *DestinationSpec) String() string { return proto.CompactTextString(m) }
func (*DestinationSpec) ProtoMessage()    {}
func (*DestinationSpec) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae47d2df5fad2a45, []int{5}
}
func (m *DestinationSpec) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DestinationSpec.Unmarshal(m, b)
}
func (m *DestinationSpec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DestinationSpec.Marshal(b, m, deterministic)
}
func (m *DestinationSpec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DestinationSpec.Merge(m, src)
}
func (m *DestinationSpec) XXX_Size() int {
	return xxx_messageInfo_DestinationSpec.Size(m)
}
func (m *DestinationSpec) XXX_DiscardUnknown() {
	xxx_messageInfo_DestinationSpec.DiscardUnknown(m)
}

var xxx_messageInfo_DestinationSpec proto.InternalMessageInfo

type isDestinationSpec_DestinationType interface {
	isDestinationSpec_DestinationType()
	Equal(interface{}) bool
}

type DestinationSpec_Aws struct {
	Aws *aws.DestinationSpec `protobuf:"bytes,1,opt,name=aws,proto3,oneof" json:"aws,omitempty"`
}
type DestinationSpec_Azure struct {
	Azure *azure.DestinationSpec `protobuf:"bytes,2,opt,name=azure,proto3,oneof" json:"azure,omitempty"`
}
type DestinationSpec_Rest struct {
	Rest *rest.DestinationSpec `protobuf:"bytes,3,opt,name=rest,proto3,oneof" json:"rest,omitempty"`
}
type DestinationSpec_Grpc struct {
	Grpc *grpc.DestinationSpec `protobuf:"bytes,4,opt,name=grpc,proto3,oneof" json:"grpc,omitempty"`
}

func (*DestinationSpec_Aws) isDestinationSpec_DestinationType()   {}
func (*DestinationSpec_Azure) isDestinationSpec_DestinationType() {}
func (*DestinationSpec_Rest) isDestinationSpec_DestinationType()  {}
func (*DestinationSpec_Grpc) isDestinationSpec_DestinationType()  {}

func (m *DestinationSpec) GetDestinationType() isDestinationSpec_DestinationType {
	if m != nil {
		return m.DestinationType
	}
	return nil
}

func (m *DestinationSpec) GetAws() *aws.DestinationSpec {
	if x, ok := m.GetDestinationType().(*DestinationSpec_Aws); ok {
		return x.Aws
	}
	return nil
}

func (m *DestinationSpec) GetAzure() *azure.DestinationSpec {
	if x, ok := m.GetDestinationType().(*DestinationSpec_Azure); ok {
		return x.Azure
	}
	return nil
}

func (m *DestinationSpec) GetRest() *rest.DestinationSpec {
	if x, ok := m.GetDestinationType().(*DestinationSpec_Rest); ok {
		return x.Rest
	}
	return nil
}

func (m *DestinationSpec) GetGrpc() *grpc.DestinationSpec {
	if x, ok := m.GetDestinationType().(*DestinationSpec_Grpc); ok {
		return x.Grpc
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*DestinationSpec) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*DestinationSpec_Aws)(nil),
		(*DestinationSpec_Azure)(nil),
		(*DestinationSpec_Rest)(nil),
		(*DestinationSpec_Grpc)(nil),
	}
}

// Plugin-specific configuration that is applied when a specific weighted destination
// is selected for routing.
type WeightedDestinationPlugins struct {
	// Append/Remove headers on Requests or Responses to/from this Weighted Destination
	HeaderManipulation *headers.HeaderManipulation `protobuf:"bytes,1,opt,name=header_manipulation,json=headerManipulation,proto3" json:"header_manipulation,omitempty"`
	// Transformations to apply
	Transformations      *transformation.RouteTransformations `protobuf:"bytes,2,opt,name=transformations,proto3" json:"transformations,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                             `json:"-"`
	XXX_unrecognized     []byte                               `json:"-"`
	XXX_sizecache        int32                                `json:"-"`
}

func (m *WeightedDestinationPlugins) Reset()         { *m = WeightedDestinationPlugins{} }
func (m *WeightedDestinationPlugins) String() string { return proto.CompactTextString(m) }
func (*WeightedDestinationPlugins) ProtoMessage()    {}
func (*WeightedDestinationPlugins) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae47d2df5fad2a45, []int{6}
}
func (m *WeightedDestinationPlugins) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WeightedDestinationPlugins.Unmarshal(m, b)
}
func (m *WeightedDestinationPlugins) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WeightedDestinationPlugins.Marshal(b, m, deterministic)
}
func (m *WeightedDestinationPlugins) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WeightedDestinationPlugins.Merge(m, src)
}
func (m *WeightedDestinationPlugins) XXX_Size() int {
	return xxx_messageInfo_WeightedDestinationPlugins.Size(m)
}
func (m *WeightedDestinationPlugins) XXX_DiscardUnknown() {
	xxx_messageInfo_WeightedDestinationPlugins.DiscardUnknown(m)
}

var xxx_messageInfo_WeightedDestinationPlugins proto.InternalMessageInfo

func (m *WeightedDestinationPlugins) GetHeaderManipulation() *headers.HeaderManipulation {
	if m != nil {
		return m.HeaderManipulation
	}
	return nil
}

func (m *WeightedDestinationPlugins) GetTransformations() *transformation.RouteTransformations {
	if m != nil {
		return m.Transformations
	}
	return nil
}

// Each upstream in Gloo has a type. Supported types include `static`, `kubernetes`, `aws`, `consul`, and more.
// Each upstream type is handled by a corresponding Gloo plugin.
type UpstreamSpec struct {
	SslConfig *UpstreamSslConfig `protobuf:"bytes,1,opt,name=ssl_config,json=sslConfig,proto3" json:"ssl_config,omitempty"`
	// Circuit breakers for this upstream. if not set, the defaults ones from the Gloo settings will be used.
	// if those are not set, [envoy's defaults](https://www.envoyproxy.io/docs/envoy/latest/api-v2/api/v2/cluster/circuit_breaker.proto#envoy-api-msg-cluster-circuitbreakers)
	// will be used.
	CircuitBreakers    *CircuitBreakerConfig     `protobuf:"bytes,2,opt,name=circuit_breakers,json=circuitBreakers,proto3" json:"circuit_breakers,omitempty"`
	LoadBalancerConfig *LoadBalancerConfig       `protobuf:"bytes,3,opt,name=load_balancer_config,json=loadBalancerConfig,proto3" json:"load_balancer_config,omitempty"`
	ConnectionConfig   *ConnectionConfig         `protobuf:"bytes,4,opt,name=connection_config,json=connectionConfig,proto3" json:"connection_config,omitempty"`
	HealthChecks       []*core.HealthCheck       `protobuf:"bytes,5,rep,name=health_checks,json=healthChecks,proto3" json:"health_checks,omitempty"`
	OutlierDetection   *cluster.OutlierDetection `protobuf:"bytes,6,opt,name=outlier_detection,json=outlierDetection,proto3" json:"outlier_detection,omitempty"`
	// Use http2 when communicating with this upstream
	// this field is evaluated `true` for upstreams
	// with a grpc service spec
	UseHttp2 bool `protobuf:"varint,7,opt,name=use_http2,json=useHttp2,proto3" json:"use_http2,omitempty"`
	// Note to developers: new Upstream Plugins must be added to this oneof field
	// to be usable by Gloo.
	//
	// Types that are valid to be assigned to UpstreamType:
	//	*UpstreamSpec_Kube
	//	*UpstreamSpec_Static
	//	*UpstreamSpec_Pipe
	//	*UpstreamSpec_Aws
	//	*UpstreamSpec_Azure
	//	*UpstreamSpec_Consul
	//	*UpstreamSpec_AwsEc2
	UpstreamType         isUpstreamSpec_UpstreamType `protobuf_oneof:"upstream_type"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *UpstreamSpec) Reset()         { *m = UpstreamSpec{} }
func (m *UpstreamSpec) String() string { return proto.CompactTextString(m) }
func (*UpstreamSpec) ProtoMessage()    {}
func (*UpstreamSpec) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae47d2df5fad2a45, []int{7}
}
func (m *UpstreamSpec) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpstreamSpec.Unmarshal(m, b)
}
func (m *UpstreamSpec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpstreamSpec.Marshal(b, m, deterministic)
}
func (m *UpstreamSpec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpstreamSpec.Merge(m, src)
}
func (m *UpstreamSpec) XXX_Size() int {
	return xxx_messageInfo_UpstreamSpec.Size(m)
}
func (m *UpstreamSpec) XXX_DiscardUnknown() {
	xxx_messageInfo_UpstreamSpec.DiscardUnknown(m)
}

var xxx_messageInfo_UpstreamSpec proto.InternalMessageInfo

type isUpstreamSpec_UpstreamType interface {
	isUpstreamSpec_UpstreamType()
	Equal(interface{}) bool
}

type UpstreamSpec_Kube struct {
	Kube *kubernetes.UpstreamSpec `protobuf:"bytes,8,opt,name=kube,proto3,oneof" json:"kube,omitempty"`
}
type UpstreamSpec_Static struct {
	Static *static.UpstreamSpec `protobuf:"bytes,9,opt,name=static,proto3,oneof" json:"static,omitempty"`
}
type UpstreamSpec_Pipe struct {
	Pipe *pipe.UpstreamSpec `protobuf:"bytes,10,opt,name=pipe,proto3,oneof" json:"pipe,omitempty"`
}
type UpstreamSpec_Aws struct {
	Aws *aws.UpstreamSpec `protobuf:"bytes,11,opt,name=aws,proto3,oneof" json:"aws,omitempty"`
}
type UpstreamSpec_Azure struct {
	Azure *azure.UpstreamSpec `protobuf:"bytes,12,opt,name=azure,proto3,oneof" json:"azure,omitempty"`
}
type UpstreamSpec_Consul struct {
	Consul *consul.UpstreamSpec `protobuf:"bytes,13,opt,name=consul,proto3,oneof" json:"consul,omitempty"`
}
type UpstreamSpec_AwsEc2 struct {
	AwsEc2 *ec2.UpstreamSpec `protobuf:"bytes,14,opt,name=aws_ec2,json=awsEc2,proto3,oneof" json:"aws_ec2,omitempty"`
}

func (*UpstreamSpec_Kube) isUpstreamSpec_UpstreamType()   {}
func (*UpstreamSpec_Static) isUpstreamSpec_UpstreamType() {}
func (*UpstreamSpec_Pipe) isUpstreamSpec_UpstreamType()   {}
func (*UpstreamSpec_Aws) isUpstreamSpec_UpstreamType()    {}
func (*UpstreamSpec_Azure) isUpstreamSpec_UpstreamType()  {}
func (*UpstreamSpec_Consul) isUpstreamSpec_UpstreamType() {}
func (*UpstreamSpec_AwsEc2) isUpstreamSpec_UpstreamType() {}

func (m *UpstreamSpec) GetUpstreamType() isUpstreamSpec_UpstreamType {
	if m != nil {
		return m.UpstreamType
	}
	return nil
}

func (m *UpstreamSpec) GetSslConfig() *UpstreamSslConfig {
	if m != nil {
		return m.SslConfig
	}
	return nil
}

func (m *UpstreamSpec) GetCircuitBreakers() *CircuitBreakerConfig {
	if m != nil {
		return m.CircuitBreakers
	}
	return nil
}

func (m *UpstreamSpec) GetLoadBalancerConfig() *LoadBalancerConfig {
	if m != nil {
		return m.LoadBalancerConfig
	}
	return nil
}

func (m *UpstreamSpec) GetConnectionConfig() *ConnectionConfig {
	if m != nil {
		return m.ConnectionConfig
	}
	return nil
}

func (m *UpstreamSpec) GetHealthChecks() []*core.HealthCheck {
	if m != nil {
		return m.HealthChecks
	}
	return nil
}

func (m *UpstreamSpec) GetOutlierDetection() *cluster.OutlierDetection {
	if m != nil {
		return m.OutlierDetection
	}
	return nil
}

func (m *UpstreamSpec) GetUseHttp2() bool {
	if m != nil {
		return m.UseHttp2
	}
	return false
}

func (m *UpstreamSpec) GetKube() *kubernetes.UpstreamSpec {
	if x, ok := m.GetUpstreamType().(*UpstreamSpec_Kube); ok {
		return x.Kube
	}
	return nil
}

func (m *UpstreamSpec) GetStatic() *static.UpstreamSpec {
	if x, ok := m.GetUpstreamType().(*UpstreamSpec_Static); ok {
		return x.Static
	}
	return nil
}

func (m *UpstreamSpec) GetPipe() *pipe.UpstreamSpec {
	if x, ok := m.GetUpstreamType().(*UpstreamSpec_Pipe); ok {
		return x.Pipe
	}
	return nil
}

func (m *UpstreamSpec) GetAws() *aws.UpstreamSpec {
	if x, ok := m.GetUpstreamType().(*UpstreamSpec_Aws); ok {
		return x.Aws
	}
	return nil
}

func (m *UpstreamSpec) GetAzure() *azure.UpstreamSpec {
	if x, ok := m.GetUpstreamType().(*UpstreamSpec_Azure); ok {
		return x.Azure
	}
	return nil
}

func (m *UpstreamSpec) GetConsul() *consul.UpstreamSpec {
	if x, ok := m.GetUpstreamType().(*UpstreamSpec_Consul); ok {
		return x.Consul
	}
	return nil
}

func (m *UpstreamSpec) GetAwsEc2() *ec2.UpstreamSpec {
	if x, ok := m.GetUpstreamType().(*UpstreamSpec_AwsEc2); ok {
		return x.AwsEc2
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*UpstreamSpec) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*UpstreamSpec_Kube)(nil),
		(*UpstreamSpec_Static)(nil),
		(*UpstreamSpec_Pipe)(nil),
		(*UpstreamSpec_Aws)(nil),
		(*UpstreamSpec_Azure)(nil),
		(*UpstreamSpec_Consul)(nil),
		(*UpstreamSpec_AwsEc2)(nil),
	}
}

func init() {
	proto.RegisterType((*ListenerPlugins)(nil), "gloo.solo.io.ListenerPlugins")
	proto.RegisterType((*HttpListenerPlugins)(nil), "gloo.solo.io.HttpListenerPlugins")
	proto.RegisterType((*TcpListenerPlugins)(nil), "gloo.solo.io.TcpListenerPlugins")
	proto.RegisterType((*VirtualHostPlugins)(nil), "gloo.solo.io.VirtualHostPlugins")
	proto.RegisterType((*RoutePlugins)(nil), "gloo.solo.io.RoutePlugins")
	proto.RegisterType((*DestinationSpec)(nil), "gloo.solo.io.DestinationSpec")
	proto.RegisterType((*WeightedDestinationPlugins)(nil), "gloo.solo.io.WeightedDestinationPlugins")
	proto.RegisterType((*UpstreamSpec)(nil), "gloo.solo.io.UpstreamSpec")
}

func init() {
	proto.RegisterFile("github.com/solo-io/gloo/projects/gloo/api/v1/plugins.proto", fileDescriptor_ae47d2df5fad2a45)
}

var fileDescriptor_ae47d2df5fad2a45 = []byte{
	// 1737 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x99, 0x4f, 0x73, 0x1b, 0xb7,
	0x15, 0xc0, 0x4b, 0x4b, 0x96, 0x2c, 0x48, 0xb2, 0x64, 0xc4, 0xd3, 0x61, 0xdd, 0xd6, 0x71, 0x35,
	0xd3, 0x38, 0x76, 0xc7, 0x60, 0xca, 0x76, 0x92, 0x71, 0xa6, 0x6e, 0x6d, 0xd1, 0x4e, 0xd4, 0x46,
	0x6e, 0x34, 0x2b, 0x27, 0x76, 0x7a, 0xd9, 0x01, 0x41, 0x70, 0x17, 0xd6, 0x6a, 0xb1, 0x03, 0x60,
	0x4d, 0xa9, 0xa7, 0x7e, 0x89, 0xce, 0xf4, 0xda, 0x5b, 0x2f, 0x3d, 0xf6, 0x0b, 0xf4, 0x5b, 0xe4,
	0xd4, 0x99, 0x7e, 0x92, 0x0e, 0x80, 0xb7, 0xcb, 0x5d, 0x6a, 0x95, 0x90, 0x5c, 0xf5, 0xc0, 0xfd,
	0xfb, 0xde, 0x6f, 0x1f, 0x80, 0x87, 0xf7, 0x1e, 0x40, 0xf4, 0x69, 0x24, 0x4c, 0x9c, 0x0f, 0x09,
	0x93, 0xa7, 0x3d, 0x2d, 0x13, 0xf9, 0x48, 0xc8, 0x5e, 0x94, 0x48, 0xd9, 0xcb, 0x94, 0x7c, 0xcb,
	0x99, 0xd1, 0xfe, 0x8e, 0x66, 0xa2, 0xf7, 0xee, 0x97, 0xbd, 0x2c, 0xc9, 0x23, 0x91, 0x6a, 0x92,
	0x29, 0x69, 0x24, 0xde, 0xb2, 0xaf, 0x88, 0xd5, 0x22, 0x42, 0xde, 0xf9, 0x49, 0x24, 0x65, 0x94,
	0xf0, 0x9e, 0x7b, 0x37, 0xcc, 0xc7, 0x3d, 0x6d, 0x54, 0xce, 0x8c, 0x97, 0xbd, 0x73, 0x3b, 0x92,
	0x91, 0x74, 0x97, 0x3d, 0x7b, 0x05, 0x4f, 0x3f, 0x5e, 0xe8, 0xeb, 0x5a, 0x27, 0xa0, 0xf7, 0x64,
	0x21, 0x3d, 0x7e, 0x66, 0x78, 0xaa, 0x85, 0x2c, 0x0c, 0xbf, 0xb3, 0xbf, 0x90, 0x3a, 0x13, 0x8a,
	0xe5, 0xc2, 0x84, 0x43, 0xc5, 0xe9, 0x09, 0x57, 0xc0, 0x78, 0xba, 0x10, 0x23, 0x91, 0x74, 0x14,
	0x0e, 0x69, 0x42, 0x53, 0x56, 0x12, 0x16, 0x6b, 0x04, 0x93, 0x69, 0xca, 0x99, 0x11, 0x32, 0x5d,
	0xaa, 0x11, 0x30, 0x72, 0x3d, 0x3a, 0x71, 0x3f, 0x60, 0xfc, 0x61, 0x69, 0x06, 0x67, 0x7d, 0x7b,
	0x0e, 0x39, 0xeb, 0x03, 0xeb, 0xf9, 0x52, 0x2c, 0x26, 0x95, 0x3f, 0xb4, 0xa2, 0x28, 0xae, 0x8d,
	0x3b, 0xb4, 0xa2, 0x44, 0x2a, 0x63, 0xee, 0xd0, 0xae, 0x87, 0x13, 0xf7, 0x03, 0xc6, 0xe1, 0xd2,
	0x96, 0x84, 0x13, 0x3e, 0x2c, 0x2f, 0x5a, 0x59, 0x14, 0xb3, 0x53, 0xfb, 0x03, 0xc6, 0xc1, 0x52,
	0x8c, 0x64, 0x18, 0x53, 0x1d, 0xc3, 0x09, 0x48, 0x7f, 0x5c, 0x8a, 0xa4, 0x63, 0x3a, 0x92, 0x13,
	0x91, 0x46, 0xd3, 0xab, 0x56, 0xad, 0x33, 0x2c, 0xb3, 0xbf, 0x56, 0x1e, 0x6d, 0x14, 0x65, 0xd6,
	0x22, 0x38, 0x03, 0xeb, 0xb3, 0xe5, 0xc6, 0xff, 0xcf, 0xb9, 0xe2, 0xfe, 0xd8, 0xaa, 0xc7, 0x99,
	0x4c, 0x75, 0x9e, 0xc0, 0x09, 0x48, 0x47, 0x4b, 0x91, 0x4e, 0xf2, 0x21, 0x57, 0x29, 0x37, 0xbc,
	0x7a, 0xd9, 0xaa, 0xbf, 0x14, 0x37, 0x4a, 0xf0, 0xf2, 0xdc, 0xaa, 0x9d, 0xda, 0x50, 0x23, 0x18,
	0x9c, 0x5a, 0xcd, 0xdf, 0x4c, 0x64, 0xdc, 0x1d, 0x5a, 0x8d, 0x9f, 0x35, 0x04, 0x8e, 0xc0, 0x79,
	0xb3, 0xac, 0x4f, 0xa5, 0x7a, 0x2c, 0xd5, 0x29, 0xb5, 0x41, 0xbb, 0x97, 0x29, 0x3e, 0x16, 0x67,
	0xa1, 0xe2, 0x13, 0x25, 0x0c, 0xbf, 0x4a, 0x72, 0xfd, 0x16, 0xc8, 0x5f, 0x2e, 0x45, 0x1e, 0xd3,
	0x3c, 0x31, 0x22, 0x7d, 0xeb, 0x13, 0x8d, 0xbf, 0x6d, 0xe5, 0x28, 0x31, 0xa7, 0x23, 0xae, 0xca,
	0x33, 0xb0, 0x82, 0x65, 0x59, 0x89, 0x89, 0x59, 0xcc, 0xd9, 0x49, 0xf5, 0xba, 0x1d, 0x53, 0x6a,
	0x03, 0x43, 0x52, 0xbd, 0x06, 0xe6, 0x57, 0x8b, 0x95, 0x19, 0xa9, 0xe1, 0x2a, 0x53, 0x42, 0xf3,
	0x12, 0xcf, 0xcf, 0x0c, 0xcd, 0x4d, 0x5c, 0x9c, 0x01, 0xfb, 0xb2, 0x2d, 0xf6, 0xed, 0xc4, 0xd8,
	0x1f, 0xe0, 0xbe, 0x69, 0x8b, 0x53, 0xd4, 0xf0, 0x44, 0x9c, 0x0a, 0x33, 0xbd, 0x5a, 0xca, 0x8b,
	0x9a, 0xd0, 0x43, 0xca, 0xdc, 0xe1, 0xaa, 0x9a, 0x3e, 0xa1, 0x63, 0xfb, 0x03, 0x5c, 0x38, 0x3f,
	0xce, 0x16, 0x81, 0x2a, 0xa5, 0x49, 0x8f, 0xa7, 0xef, 0xe4, 0xb9, 0xff, 0x42, 0xbf, 0xc7, 0x92,
	0x5c, 0x1b, 0xae, 0x7a, 0x32, 0x37, 0x89, 0xe0, 0x2a, 0x1c, 0x71, 0x53, 0x2b, 0xb2, 0x5e, 0xb7,
	0xfe, 0x80, 0x54, 0x1c, 0xbc, 0x35, 0xac, 0xba, 0xeb, 0xdd, 0xd9, 0x6a, 0x79, 0x94, 0xab, 0xca,
	0xfc, 0xdd, 0xfb, 0x57, 0x07, 0xed, 0x1c, 0x0a, 0x6d, 0x78, 0xca, 0xd5, 0x91, 0x6f, 0x3b, 0x1e,
	0xa1, 0x1f, 0x52, 0xc6, 0xb8, 0xd6, 0x61, 0x22, 0xa3, 0x48, 0xa4, 0x51, 0xa8, 0xb9, 0x7a, 0x27,
	0x18, 0xef, 0x76, 0xee, 0x75, 0x3e, 0xdc, 0xec, 0x13, 0xe2, 0xea, 0x0e, 0xa8, 0xd1, 0xab, 0xc5,
	0x39, 0x79, 0xe6, 0xf4, 0x0e, 0xbd, 0xda, 0xb1, 0xd7, 0x0a, 0x6e, 0xd3, 0x86, 0xa7, 0xf8, 0x37,
	0x08, 0x4d, 0x0b, 0xe6, 0xee, 0x35, 0x47, 0xee, 0xd6, 0x69, 0x2f, 0xca, 0xf7, 0xfb, 0xd7, 0xba,
	0x9d, 0xa0, 0x22, 0xbf, 0xf7, 0xf7, 0x15, 0xf4, 0xde, 0x81, 0x31, 0xd9, 0xac, 0xed, 0xcf, 0xd0,
	0x8d, 0xa2, 0x96, 0x01, 0x6b, 0x3f, 0x20, 0xd3, 0xe2, 0xa6, 0xc9, 0xe4, 0xcf, 0x55, 0xc6, 0x5e,
	0xf3, 0x61, 0xb0, 0x1e, 0xf9, 0x0b, 0xfc, 0x97, 0x0e, 0xba, 0x17, 0x1b, 0x93, 0x85, 0xd3, 0x52,
	0x38, 0x3c, 0xa5, 0x29, 0x8d, 0xb8, 0x0a, 0x35, 0x37, 0x46, 0xa4, 0x51, 0x61, 0xef, 0x27, 0xc4,
	0xd5, 0x3b, 0x4d, 0x58, 0x6b, 0xdc, 0xa0, 0x04, 0xbc, 0xf4, 0xfa, 0xc7, 0xa0, 0x1e, 0xfc, 0x34,
	0xfe, 0xae, 0xd7, 0xf8, 0x08, 0x6d, 0x55, 0xc7, 0xb2, 0xbb, 0xea, 0xbe, 0xf6, 0x88, 0xd4, 0xc2,
	0x51, 0xe3, 0x57, 0x9d, 0xc0, 0xc0, 0x0a, 0x04, 0x9b, 0xf1, 0xf4, 0x66, 0xa6, 0xb7, 0x57, 0x16,
	0xeb, 0x6d, 0xfc, 0x6b, 0xb4, 0x32, 0xa1, 0xe3, 0xee, 0x75, 0xa7, 0xb6, 0x47, 0xdc, 0xc4, 0x68,
	0xfa, 0x7c, 0xd9, 0x3e, 0x2b, 0xbe, 0x97, 0x22, 0xfc, 0x8a, 0x5d, 0x18, 0xa1, 0x37, 0x08, 0x1b,
	0x96, 0x85, 0x99, 0x92, 0x67, 0xe7, 0xd3, 0xfe, 0xf4, 0x16, 0x3d, 0x24, 0xae, 0xc2, 0x6a, 0x42,
	0xbf, 0x62, 0xd9, 0x91, 0x55, 0x29, 0x3f, 0xb1, 0x6b, 0x66, 0x9e, 0xec, 0xfd, 0xfb, 0x3a, 0xc2,
	0x5f, 0x0b, 0x65, 0x72, 0x9a, 0x1c, 0x48, 0x6d, 0x8a, 0x0f, 0xd6, 0x9b, 0xde, 0x59, 0xb0, 0xe9,
	0x03, 0xb4, 0x0e, 0xd5, 0x07, 0x34, 0xff, 0x01, 0x29, 0xab, 0x91, 0x26, 0x3b, 0x03, 0x6e, 0xd4,
	0xf9, 0x91, 0x4c, 0x04, 0x3b, 0x0f, 0x0a, 0x4d, 0xfc, 0x09, 0xba, 0xee, 0x12, 0x7d, 0x17, 0x39,
	0xc4, 0xcf, 0x08, 0xa4, 0xfd, 0xc6, 0x3e, 0xb4, 0xaf, 0x02, 0x2f, 0x8f, 0x29, 0x7a, 0xcf, 0xa7,
	0x34, 0xeb, 0x81, 0x22, 0xcb, 0x13, 0x37, 0x77, 0xc1, 0xfb, 0x3e, 0x22, 0x65, 0xba, 0xbb, 0xc4,
	0x17, 0x46, 0x5c, 0xbd, 0xac, 0xe8, 0x05, 0x38, 0xbe, 0xf0, 0x0c, 0x3f, 0x46, 0xab, 0x76, 0x5d,
	0x04, 0x23, 0xf0, 0x73, 0xe2, 0x17, 0x49, 0x4d, 0xc0, 0x81, 0x54, 0x1a, 0x5a, 0xe6, 0x54, 0xf0,
	0x1b, 0xb4, 0x53, 0x2f, 0x0a, 0x34, 0x78, 0x2a, 0x21, 0x2e, 0x38, 0x11, 0x9a, 0x09, 0xf2, 0xae,
	0x4f, 0xc6, 0x22, 0x31, 0x5c, 0x11, 0xeb, 0xf3, 0x24, 0x90, 0xb9, 0xe1, 0xaf, 0xea, 0x5a, 0xc1,
	0x2c, 0x06, 0xbf, 0x46, 0x37, 0xcb, 0x1c, 0x11, 0x5a, 0x23, 0xba, 0x6b, 0xd0, 0xe4, 0x4a, 0xea,
	0x68, 0xb2, 0xf1, 0xf7, 0x69, 0xa4, 0xb8, 0xd6, 0x01, 0x35, 0xfc, 0xd0, 0x4a, 0x05, 0xdb, 0xa5,
	0xc2, 0xe7, 0x89, 0x94, 0x78, 0x84, 0x6e, 0x4d, 0xc1, 0x94, 0x79, 0xa3, 0xd7, 0x61, 0x32, 0x7f,
	0x0f, 0xbb, 0x84, 0x7e, 0x6d, 0x53, 0x78, 0xe9, 0x33, 0xc1, 0x6e, 0xa9, 0xf7, 0xcc, 0x03, 0xf1,
	0x63, 0x3f, 0x5f, 0x6e, 0x38, 0xee, 0xfd, 0xcb, 0xe7, 0x8b, 0x03, 0xd5, 0x27, 0xcd, 0x5f, 0x37,
	0xd0, 0x96, 0xeb, 0xa3, 0xe9, 0x7c, 0xb9, 0xd0, 0xc9, 0x9d, 0xab, 0xe9, 0xe4, 0xdf, 0xa1, 0x35,
	0x57, 0x79, 0x15, 0xd1, 0xec, 0x3e, 0x81, 0x42, 0xac, 0xb1, 0xf1, 0x16, 0xf9, 0x99, 0x13, 0x0f,
	0x40, 0x0d, 0x7f, 0x83, 0x6e, 0xd6, 0xcb, 0x4d, 0x70, 0xa2, 0x3e, 0x99, 0xad, 0x15, 0x9b, 0x88,
	0x47, 0x4e, 0x35, 0xf0, 0x9a, 0xc1, 0x76, 0x56, 0xbd, 0xc5, 0x8f, 0xd1, 0xba, 0x11, 0xa7, 0x5c,
	0xe6, 0x06, 0x5c, 0xea, 0x47, 0xc4, 0x67, 0x32, 0x52, 0x64, 0x32, 0xf2, 0x1c, 0x32, 0xd9, 0xfe,
	0xea, 0xdf, 0xfe, 0xf3, 0x7e, 0x27, 0x28, 0xe4, 0xaf, 0x66, 0xc6, 0xd6, 0x83, 0xc6, 0xda, 0x82,
	0x41, 0xe3, 0x10, 0xad, 0xc3, 0x12, 0x0f, 0x7c, 0xcb, 0xf5, 0x88, 0x5f, 0xf2, 0x5d, 0xda, 0xb9,
	0xaf, 0xbc, 0x44, 0xe9, 0x0e, 0x05, 0x02, 0x1f, 0xa2, 0x8d, 0x72, 0x09, 0x0b, 0x3e, 0x45, 0x48,
	0x65, 0x51, 0x7b, 0x29, 0xf1, 0xb8, 0x90, 0x09, 0xa6, 0x80, 0xcb, 0x42, 0xca, 0xc6, 0x15, 0x86,
	0x14, 0x9b, 0xbe, 0xa4, 0x36, 0xa5, 0x57, 0xa0, 0x22, 0x7d, 0x55, 0x2b, 0xdf, 0x46, 0xbe, 0xd4,
	0xa6, 0x70, 0x88, 0xcd, 0x78, 0x7a, 0x53, 0x06, 0xa9, 0xcd, 0xc5, 0x83, 0xd4, 0x17, 0x68, 0x3d,
	0x19, 0x86, 0x31, 0xd5, 0x71, 0x77, 0x0b, 0xc6, 0xa2, 0xd8, 0x5d, 0xb8, 0xb4, 0xe3, 0xfc, 0x3c,
	0x3e, 0xa0, 0x3a, 0x1e, 0xc8, 0x74, 0x2c, 0xa2, 0x60, 0x2d, 0x19, 0xda, 0xbb, 0x86, 0xb8, 0xb4,
	0xfd, 0x7f, 0x8c, 0x4b, 0x37, 0x17, 0x8c, 0x4b, 0xce, 0xf6, 0x39, 0xe2, 0xd2, 0xce, 0xf7, 0xc5,
	0x25, 0xef, 0x3d, 0xb5, 0xb8, 0xf4, 0xcf, 0x6b, 0x68, 0xe7, 0x39, 0xd7, 0x46, 0xa4, 0x6e, 0x8c,
	0x8f, 0x33, 0xce, 0xf0, 0x13, 0xb4, 0x42, 0x27, 0x45, 0x38, 0x7a, 0x40, 0xdc, 0x7e, 0x5f, 0x13,
	0x6e, 0x46, 0xef, 0xe0, 0x07, 0x81, 0xd5, 0xc3, 0x03, 0x74, 0xdd, 0x6d, 0x5f, 0x40, 0xf8, 0xf9,
	0x05, 0x81, 0xcd, 0x8c, 0xf9, 0x10, 0x5e, 0x17, 0x3f, 0x45, 0xab, 0x8a, 0x6b, 0x53, 0x16, 0x10,
	0x7e, 0x77, 0x6e, 0x3e, 0x84, 0xd3, 0xb4, 0x04, 0x5b, 0xfa, 0x41, 0x9c, 0x79, 0x48, 0xfc, 0xce,
	0xdc, 0x9c, 0x04, 0x2b, 0xbc, 0x8f, 0xd1, 0xee, 0x68, 0xfa, 0x2a, 0x34, 0xe7, 0x19, 0xdf, 0xfb,
	0xb6, 0x83, 0xee, 0xbc, 0xe6, 0x22, 0x8a, 0x0d, 0x1f, 0x55, 0xf4, 0x8a, 0xa8, 0x7e, 0xc9, 0x2c,
	0xec, 0x5c, 0xe1, 0x2c, 0x6c, 0x48, 0x1c, 0xd7, 0xae, 0x24, 0x71, 0xec, 0x7d, 0xbb, 0x8e, 0xb6,
	0xbe, 0xca, 0xec, 0x5c, 0xa6, 0xa7, 0xce, 0x11, 0x7e, 0x8b, 0x90, 0xd6, 0x89, 0x2d, 0x98, 0xc7,
	0x22, 0x82, 0x46, 0xbc, 0x5f, 0x37, 0xba, 0x94, 0xd7, 0x09, 0xcc, 0xa9, 0x0d, 0x5d, 0x5c, 0xe2,
	0x97, 0x68, 0x77, 0x66, 0xf7, 0xbb, 0xb0, 0x75, 0x6f, 0x66, 0x76, 0x7b, 0xa9, 0x7d, 0x2f, 0x04,
	0xa0, 0x1d, 0x56, 0x7b, 0xaa, 0x71, 0x80, 0x6e, 0xd7, 0x36, 0xc2, 0x0b, 0xc3, 0xbc, 0x8f, 0xdc,
	0xab, 0x23, 0x0f, 0x25, 0x1d, 0xed, 0x83, 0x20, 0x00, 0x71, 0x72, 0xe1, 0x19, 0xfe, 0x02, 0xdd,
	0xaa, 0xac, 0x07, 0x00, 0xe8, 0x5d, 0xe6, 0xee, 0x6c, 0x04, 0x2a, 0xc4, 0x00, 0xb7, 0xcb, 0x66,
	0x9e, 0xe0, 0x01, 0xda, 0xae, 0xd6, 0xf7, 0x36, 0x51, 0xad, 0x38, 0x50, 0x6d, 0x60, 0xec, 0x9a,
	0xae, 0x56, 0xd1, 0x6f, 0x55, 0x2a, 0x7a, 0x8d, 0x8f, 0xd1, 0xad, 0x0b, 0xcb, 0x49, 0xc8, 0x54,
	0x1f, 0xcc, 0x80, 0xfc, 0xea, 0x93, 0x7c, 0xe9, 0xc5, 0x9f, 0x17, 0xd2, 0xc1, 0xae, 0x9c, 0x79,
	0x82, 0x7f, 0x8c, 0x36, 0x72, 0xcd, 0x43, 0xeb, 0x0c, 0x7d, 0x97, 0xbb, 0x6e, 0x04, 0x37, 0x72,
	0xcd, 0xed, 0x6a, 0xa6, 0x8f, 0x07, 0x68, 0xf5, 0x24, 0x1f, 0x72, 0xc8, 0x41, 0x8f, 0x48, 0x75,
	0x97, 0xaf, 0xc9, 0x51, 0xab, 0x3e, 0x62, 0x27, 0x8b, 0x95, 0xc7, 0x03, 0xb4, 0xe6, 0xf7, 0xe0,
	0x20, 0xe5, 0x3c, 0x20, 0xc5, 0x96, 0xdc, 0x1c, 0x08, 0x50, 0xc5, 0x4f, 0xd0, 0x6a, 0x26, 0xb2,
	0x22, 0xb3, 0xdc, 0x27, 0x7e, 0x37, 0x6e, 0x1e, 0x1b, 0xac, 0x24, 0xfe, 0xd4, 0x07, 0xae, 0x4d,
	0xe8, 0xac, 0x4b, 0x03, 0xd7, 0x8c, 0xb2, 0x8b, 0x5a, 0x4f, 0x8b, 0xa8, 0xe5, 0xb3, 0xc9, 0x87,
	0xdf, 0x15, 0xb5, 0x66, 0xf4, 0x21, 0x64, 0x0d, 0xd0, 0x9a, 0xdf, 0x6d, 0x85, 0xe4, 0xf1, 0x80,
	0x14, 0x9b, 0xaf, 0xf3, 0xf4, 0x80, 0x97, 0xc5, 0x2f, 0xd0, 0x3a, 0xfc, 0x2f, 0x02, 0x69, 0xe2,
	0x21, 0x29, 0xff, 0x27, 0x99, 0x07, 0x43, 0x27, 0xfa, 0x05, 0xeb, 0xef, 0xef, 0xa0, 0xed, 0x1c,
	0xde, 0xb8, 0xb8, 0xb5, 0xff, 0xf1, 0x3f, 0xfe, 0x7b, 0xb7, 0xf3, 0xa7, 0x8f, 0xe6, 0xdb, 0x8f,
	0xc8, 0x4e, 0x22, 0xd8, 0x43, 0x19, 0xae, 0xb9, 0xba, 0xec, 0x57, 0xff, 0x0b, 0x00, 0x00, 0xff,
	0xff, 0x94, 0xfe, 0x8f, 0xa1, 0xe9, 0x1b, 0x00, 0x00,
}

func (this *ListenerPlugins) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*ListenerPlugins)
	if !ok {
		that2, ok := that.(ListenerPlugins)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.AccessLoggingService.Equal(that1.AccessLoggingService) {
		return false
	}
	if !this.Extensions.Equal(that1.Extensions) {
		return false
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}
func (this *HttpListenerPlugins) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*HttpListenerPlugins)
	if !ok {
		that2, ok := that.(HttpListenerPlugins)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.GrpcWeb.Equal(that1.GrpcWeb) {
		return false
	}
	if !this.HttpConnectionManagerSettings.Equal(that1.HttpConnectionManagerSettings) {
		return false
	}
	if !this.HealthCheck.Equal(that1.HealthCheck) {
		return false
	}
	if !this.Extensions.Equal(that1.Extensions) {
		return false
	}
	if !this.Waf.Equal(that1.Waf) {
		return false
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}
func (this *TcpListenerPlugins) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*TcpListenerPlugins)
	if !ok {
		that2, ok := that.(TcpListenerPlugins)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.TcpProxySettings.Equal(that1.TcpProxySettings) {
		return false
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}
func (this *VirtualHostPlugins) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*VirtualHostPlugins)
	if !ok {
		that2, ok := that.(VirtualHostPlugins)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.Extensions.Equal(that1.Extensions) {
		return false
	}
	if !this.Retries.Equal(that1.Retries) {
		return false
	}
	if !this.Stats.Equal(that1.Stats) {
		return false
	}
	if !this.HeaderManipulation.Equal(that1.HeaderManipulation) {
		return false
	}
	if !this.Cors.Equal(that1.Cors) {
		return false
	}
	if !this.Transformations.Equal(that1.Transformations) {
		return false
	}
	if !this.RatelimitGloo.Equal(that1.RatelimitGloo) {
		return false
	}
	if !this.RatelimitActions.Equal(that1.RatelimitActions) {
		return false
	}
	if !this.Waf.Equal(that1.Waf) {
		return false
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}
func (this *RoutePlugins) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*RoutePlugins)
	if !ok {
		that2, ok := that.(RoutePlugins)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.Transformations.Equal(that1.Transformations) {
		return false
	}
	if !this.Faults.Equal(that1.Faults) {
		return false
	}
	if !this.PrefixRewrite.Equal(that1.PrefixRewrite) {
		return false
	}
	if this.Timeout != nil && that1.Timeout != nil {
		if *this.Timeout != *that1.Timeout {
			return false
		}
	} else if this.Timeout != nil {
		return false
	} else if that1.Timeout != nil {
		return false
	}
	if !this.Retries.Equal(that1.Retries) {
		return false
	}
	if !this.Extensions.Equal(that1.Extensions) {
		return false
	}
	if !this.Tracing.Equal(that1.Tracing) {
		return false
	}
	if !this.Shadowing.Equal(that1.Shadowing) {
		return false
	}
	if !this.HeaderManipulation.Equal(that1.HeaderManipulation) {
		return false
	}
	if !this.HostRewrite.Equal(that1.HostRewrite) {
		return false
	}
	if !this.Cors.Equal(that1.Cors) {
		return false
	}
	if !this.LbHash.Equal(that1.LbHash) {
		return false
	}
	if !this.RatelimitGloo.Equal(that1.RatelimitGloo) {
		return false
	}
	if !this.RatelimitActions.Equal(that1.RatelimitActions) {
		return false
	}
	if !this.Waf.Equal(that1.Waf) {
		return false
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}
func (this *DestinationSpec) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*DestinationSpec)
	if !ok {
		that2, ok := that.(DestinationSpec)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if that1.DestinationType == nil {
		if this.DestinationType != nil {
			return false
		}
	} else if this.DestinationType == nil {
		return false
	} else if !this.DestinationType.Equal(that1.DestinationType) {
		return false
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}
func (this *DestinationSpec_Aws) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*DestinationSpec_Aws)
	if !ok {
		that2, ok := that.(DestinationSpec_Aws)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.Aws.Equal(that1.Aws) {
		return false
	}
	return true
}
func (this *DestinationSpec_Azure) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*DestinationSpec_Azure)
	if !ok {
		that2, ok := that.(DestinationSpec_Azure)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.Azure.Equal(that1.Azure) {
		return false
	}
	return true
}
func (this *DestinationSpec_Rest) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*DestinationSpec_Rest)
	if !ok {
		that2, ok := that.(DestinationSpec_Rest)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.Rest.Equal(that1.Rest) {
		return false
	}
	return true
}
func (this *DestinationSpec_Grpc) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*DestinationSpec_Grpc)
	if !ok {
		that2, ok := that.(DestinationSpec_Grpc)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.Grpc.Equal(that1.Grpc) {
		return false
	}
	return true
}
func (this *WeightedDestinationPlugins) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*WeightedDestinationPlugins)
	if !ok {
		that2, ok := that.(WeightedDestinationPlugins)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.HeaderManipulation.Equal(that1.HeaderManipulation) {
		return false
	}
	if !this.Transformations.Equal(that1.Transformations) {
		return false
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}
func (this *UpstreamSpec) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*UpstreamSpec)
	if !ok {
		that2, ok := that.(UpstreamSpec)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.SslConfig.Equal(that1.SslConfig) {
		return false
	}
	if !this.CircuitBreakers.Equal(that1.CircuitBreakers) {
		return false
	}
	if !this.LoadBalancerConfig.Equal(that1.LoadBalancerConfig) {
		return false
	}
	if !this.ConnectionConfig.Equal(that1.ConnectionConfig) {
		return false
	}
	if len(this.HealthChecks) != len(that1.HealthChecks) {
		return false
	}
	for i := range this.HealthChecks {
		if !this.HealthChecks[i].Equal(that1.HealthChecks[i]) {
			return false
		}
	}
	if !this.OutlierDetection.Equal(that1.OutlierDetection) {
		return false
	}
	if this.UseHttp2 != that1.UseHttp2 {
		return false
	}
	if that1.UpstreamType == nil {
		if this.UpstreamType != nil {
			return false
		}
	} else if this.UpstreamType == nil {
		return false
	} else if !this.UpstreamType.Equal(that1.UpstreamType) {
		return false
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}
func (this *UpstreamSpec_Kube) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*UpstreamSpec_Kube)
	if !ok {
		that2, ok := that.(UpstreamSpec_Kube)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.Kube.Equal(that1.Kube) {
		return false
	}
	return true
}
func (this *UpstreamSpec_Static) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*UpstreamSpec_Static)
	if !ok {
		that2, ok := that.(UpstreamSpec_Static)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.Static.Equal(that1.Static) {
		return false
	}
	return true
}
func (this *UpstreamSpec_Pipe) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*UpstreamSpec_Pipe)
	if !ok {
		that2, ok := that.(UpstreamSpec_Pipe)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.Pipe.Equal(that1.Pipe) {
		return false
	}
	return true
}
func (this *UpstreamSpec_Aws) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*UpstreamSpec_Aws)
	if !ok {
		that2, ok := that.(UpstreamSpec_Aws)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.Aws.Equal(that1.Aws) {
		return false
	}
	return true
}
func (this *UpstreamSpec_Azure) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*UpstreamSpec_Azure)
	if !ok {
		that2, ok := that.(UpstreamSpec_Azure)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.Azure.Equal(that1.Azure) {
		return false
	}
	return true
}
func (this *UpstreamSpec_Consul) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*UpstreamSpec_Consul)
	if !ok {
		that2, ok := that.(UpstreamSpec_Consul)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.Consul.Equal(that1.Consul) {
		return false
	}
	return true
}
func (this *UpstreamSpec_AwsEc2) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*UpstreamSpec_AwsEc2)
	if !ok {
		that2, ok := that.(UpstreamSpec_AwsEc2)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.AwsEc2.Equal(that1.AwsEc2) {
		return false
	}
	return true
}
