// Code generated by protoc-gen-ext. DO NOT EDIT.
// source: github.com/solo-io/gloo/projects/gloo/api/v1/options/dynamic_forward_proxy/dynamic_forward_proxy.proto

package dynamic_forward_proxy

import (
	"bytes"
	"encoding/binary"
	"errors"
	"fmt"
	"strings"

	"github.com/golang/protobuf/proto"
	equality "github.com/solo-io/protoc-gen-ext/pkg/equality"
)

// ensure the imports are used
var (
	_ = errors.New("")
	_ = fmt.Print
	_ = binary.LittleEndian
	_ = bytes.Compare
	_ = strings.Compare
	_ = equality.Equalizer(nil)
	_ = proto.Message(nil)
)

// Equal function
func (m *FilterConfig) Equal(that interface{}) bool {
	if that == nil {
		return m == nil
	}

	target, ok := that.(*FilterConfig)
	if !ok {
		that2, ok := that.(FilterConfig)
		if ok {
			target = &that2
		} else {
			return false
		}
	}
	if target == nil {
		return m == nil
	} else if m == nil {
		return false
	}

	if h, ok := interface{}(m.GetDnsCacheConfig()).(equality.Equalizer); ok {
		if !h.Equal(target.GetDnsCacheConfig()) {
			return false
		}
	} else {
		if !proto.Equal(m.GetDnsCacheConfig(), target.GetDnsCacheConfig()) {
			return false
		}
	}

	return true
}

// Equal function
func (m *DnsCacheCircuitBreakers) Equal(that interface{}) bool {
	if that == nil {
		return m == nil
	}

	target, ok := that.(*DnsCacheCircuitBreakers)
	if !ok {
		that2, ok := that.(DnsCacheCircuitBreakers)
		if ok {
			target = &that2
		} else {
			return false
		}
	}
	if target == nil {
		return m == nil
	} else if m == nil {
		return false
	}

	if h, ok := interface{}(m.GetMaxPendingRequests()).(equality.Equalizer); ok {
		if !h.Equal(target.GetMaxPendingRequests()) {
			return false
		}
	} else {
		if !proto.Equal(m.GetMaxPendingRequests(), target.GetMaxPendingRequests()) {
			return false
		}
	}

	return true
}

// Equal function
func (m *DnsCacheConfig) Equal(that interface{}) bool {
	if that == nil {
		return m == nil
	}

	target, ok := that.(*DnsCacheConfig)
	if !ok {
		that2, ok := that.(DnsCacheConfig)
		if ok {
			target = &that2
		} else {
			return false
		}
	}
	if target == nil {
		return m == nil
	} else if m == nil {
		return false
	}

	if strings.Compare(m.GetName(), target.GetName()) != 0 {
		return false
	}

	if h, ok := interface{}(m.GetDnsRefreshRate()).(equality.Equalizer); ok {
		if !h.Equal(target.GetDnsRefreshRate()) {
			return false
		}
	} else {
		if !proto.Equal(m.GetDnsRefreshRate(), target.GetDnsRefreshRate()) {
			return false
		}
	}

	if h, ok := interface{}(m.GetHostTtl()).(equality.Equalizer); ok {
		if !h.Equal(target.GetHostTtl()) {
			return false
		}
	} else {
		if !proto.Equal(m.GetHostTtl(), target.GetHostTtl()) {
			return false
		}
	}

	if h, ok := interface{}(m.GetMaxHosts()).(equality.Equalizer); ok {
		if !h.Equal(target.GetMaxHosts()) {
			return false
		}
	} else {
		if !proto.Equal(m.GetMaxHosts(), target.GetMaxHosts()) {
			return false
		}
	}

	if h, ok := interface{}(m.GetDnsCacheCircuitBreaker()).(equality.Equalizer); ok {
		if !h.Equal(target.GetDnsCacheCircuitBreaker()) {
			return false
		}
	} else {
		if !proto.Equal(m.GetDnsCacheCircuitBreaker(), target.GetDnsCacheCircuitBreaker()) {
			return false
		}
	}

	if h, ok := interface{}(m.GetDnsQueryTimeout()).(equality.Equalizer); ok {
		if !h.Equal(target.GetDnsQueryTimeout()) {
			return false
		}
	} else {
		if !proto.Equal(m.GetDnsQueryTimeout(), target.GetDnsQueryTimeout()) {
			return false
		}
	}

	return true
}

// Equal function
func (m *PerRouteConfig) Equal(that interface{}) bool {
	if that == nil {
		return m == nil
	}

	target, ok := that.(*PerRouteConfig)
	if !ok {
		that2, ok := that.(PerRouteConfig)
		if ok {
			target = &that2
		} else {
			return false
		}
	}
	if target == nil {
		return m == nil
	} else if m == nil {
		return false
	}

	switch m.HostRewriteSpecifier.(type) {

	case *PerRouteConfig_HostRewrite:
		if _, ok := target.HostRewriteSpecifier.(*PerRouteConfig_HostRewrite); !ok {
			return false
		}

		if strings.Compare(m.GetHostRewrite(), target.GetHostRewrite()) != 0 {
			return false
		}

	case *PerRouteConfig_AutoHostRewriteHeader:
		if _, ok := target.HostRewriteSpecifier.(*PerRouteConfig_AutoHostRewriteHeader); !ok {
			return false
		}

		if strings.Compare(m.GetAutoHostRewriteHeader(), target.GetAutoHostRewriteHeader()) != 0 {
			return false
		}

	default:
		// m is nil but target is not nil
		if m.HostRewriteSpecifier != target.HostRewriteSpecifier {
			return false
		}
	}

	return true
}
