apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TCPRoute
metadata:
  name: route
spec:
  parentRefs:
  - name: example-gateway
  rules:
  - backendRefs:
    - name: tcpbin-com
      group: gateway.kgateway.dev
      kind: Backend
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: example-gateway
spec:
  gatewayClassName: kgateway
  listeners:
  - name: tcp
    protocol: TCP
    port: 8080
  # - name: tls # does the listener even matter 
  #   protocol: HTTP
  #   port: 443
  #   tls:
  #     mode: Terminate
      # certificateRefs:
      # - name: tls-secret
      #   namespace: default
---
apiVersion: gateway.kgateway.dev/v1alpha1
kind: Backend
metadata:
  name: tcpbin-com
  namespace: default
spec:
  type: Static
  static:
    hosts:
      - host: tcpbin.com
        port: 4243 #4243
---
kind: BackendConfigPolicy
apiVersion: gateway.kgateway.dev/v1alpha1
metadata:
  name: backend-tls-policy
spec:
  targetRefs:
    - name: tcpbin-com
      group: gateway.kgateway.dev
      kind: Backend
  tls:
    tlsOrigination: true
    sni: tcpbin.com