// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: github.com/solo-io/gloo/projects/gloo/api/v1/enterprise/plugins/dlp/dlp.proto

package dlp

import (
	bytes "bytes"
	fmt "fmt"
	math "math"

	_type "github.com/envoyproxy/go-control-plane/envoy/type"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	matchers "github.com/solo-io/gloo/projects/gloo/pkg/api/v1/core/matchers"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Action_ActionType int32

const (
	Action_CUSTOM               Action_ActionType = 0
	Action_SSN                  Action_ActionType = 1
	Action_MASTERCARD           Action_ActionType = 2
	Action_VISA                 Action_ActionType = 3
	Action_AMEX                 Action_ActionType = 4
	Action_DISCOVER             Action_ActionType = 5
	Action_JCB                  Action_ActionType = 6
	Action_DINERS_CLUB          Action_ActionType = 7
	Action_CREDIT_CARD_TRACKERS Action_ActionType = 8
	Action_ALL_CREDIT_CARDS     Action_ActionType = 9
)

var Action_ActionType_name = map[int32]string{
	0: "CUSTOM",
	1: "SSN",
	2: "MASTERCARD",
	3: "VISA",
	4: "AMEX",
	5: "DISCOVER",
	6: "JCB",
	7: "DINERS_CLUB",
	8: "CREDIT_CARD_TRACKERS",
	9: "ALL_CREDIT_CARDS",
}

var Action_ActionType_value = map[string]int32{
	"CUSTOM":               0,
	"SSN":                  1,
	"MASTERCARD":           2,
	"VISA":                 3,
	"AMEX":                 4,
	"DISCOVER":             5,
	"JCB":                  6,
	"DINERS_CLUB":          7,
	"CREDIT_CARD_TRACKERS": 8,
	"ALL_CREDIT_CARDS":     9,
}

func (x Action_ActionType) String() string {
	return proto.EnumName(Action_ActionType_name, int32(x))
}

func (Action_ActionType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_34ec831aa7b23456, []int{3, 0}
}

type Config struct {
	Actions              []*Action `protobuf:"bytes,1,rep,name=actions,proto3" json:"actions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Config) Reset()         { *m = Config{} }
func (m *Config) String() string { return proto.CompactTextString(m) }
func (*Config) ProtoMessage()    {}
func (*Config) Descriptor() ([]byte, []int) {
	return fileDescriptor_34ec831aa7b23456, []int{0}
}
func (m *Config) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Config.Unmarshal(m, b)
}
func (m *Config) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Config.Marshal(b, m, deterministic)
}
func (m *Config) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Config.Merge(m, src)
}
func (m *Config) XXX_Size() int {
	return xxx_messageInfo_Config.Size(m)
}
func (m *Config) XXX_DiscardUnknown() {
	xxx_messageInfo_Config.DiscardUnknown(m)
}

var xxx_messageInfo_Config proto.InternalMessageInfo

func (m *Config) GetActions() []*Action {
	if m != nil {
		return m.Actions
	}
	return nil
}

type FilterConfig struct {
	DlpRules             []*DlpRule `protobuf:"bytes,1,rep,name=dlp_rules,json=dlpRules,proto3" json:"dlp_rules,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *FilterConfig) Reset()         { *m = FilterConfig{} }
func (m *FilterConfig) String() string { return proto.CompactTextString(m) }
func (*FilterConfig) ProtoMessage()    {}
func (*FilterConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_34ec831aa7b23456, []int{1}
}
func (m *FilterConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FilterConfig.Unmarshal(m, b)
}
func (m *FilterConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FilterConfig.Marshal(b, m, deterministic)
}
func (m *FilterConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FilterConfig.Merge(m, src)
}
func (m *FilterConfig) XXX_Size() int {
	return xxx_messageInfo_FilterConfig.Size(m)
}
func (m *FilterConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_FilterConfig.DiscardUnknown(m)
}

var xxx_messageInfo_FilterConfig proto.InternalMessageInfo

func (m *FilterConfig) GetDlpRules() []*DlpRule {
	if m != nil {
		return m.DlpRules
	}
	return nil
}

type DlpRule struct {
	Matcher              *matchers.Matcher `protobuf:"bytes,1,opt,name=matcher,proto3" json:"matcher,omitempty"`
	Actions              []*Action         `protobuf:"bytes,2,rep,name=actions,proto3" json:"actions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *DlpRule) Reset()         { *m = DlpRule{} }
func (m *DlpRule) String() string { return proto.CompactTextString(m) }
func (*DlpRule) ProtoMessage()    {}
func (*DlpRule) Descriptor() ([]byte, []int) {
	return fileDescriptor_34ec831aa7b23456, []int{2}
}
func (m *DlpRule) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DlpRule.Unmarshal(m, b)
}
func (m *DlpRule) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DlpRule.Marshal(b, m, deterministic)
}
func (m *DlpRule) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DlpRule.Merge(m, src)
}
func (m *DlpRule) XXX_Size() int {
	return xxx_messageInfo_DlpRule.Size(m)
}
func (m *DlpRule) XXX_DiscardUnknown() {
	xxx_messageInfo_DlpRule.DiscardUnknown(m)
}

var xxx_messageInfo_DlpRule proto.InternalMessageInfo

func (m *DlpRule) GetMatcher() *matchers.Matcher {
	if m != nil {
		return m.Matcher
	}
	return nil
}

func (m *DlpRule) GetActions() []*Action {
	if m != nil {
		return m.Actions
	}
	return nil
}

type Action struct {
	ActionType           Action_ActionType `protobuf:"varint,1,opt,name=action_type,json=actionType,proto3,enum=dlp.plugins.gloo.solo.io.Action_ActionType" json:"action_type,omitempty"`
	CustomAction         *CustomAction     `protobuf:"bytes,2,opt,name=custom_action,json=customAction,proto3" json:"custom_action,omitempty"`
	Shadow               bool              `protobuf:"varint,3,opt,name=shadow,proto3" json:"shadow,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Action) Reset()         { *m = Action{} }
func (m *Action) String() string { return proto.CompactTextString(m) }
func (*Action) ProtoMessage()    {}
func (*Action) Descriptor() ([]byte, []int) {
	return fileDescriptor_34ec831aa7b23456, []int{3}
}
func (m *Action) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Action.Unmarshal(m, b)
}
func (m *Action) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Action.Marshal(b, m, deterministic)
}
func (m *Action) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Action.Merge(m, src)
}
func (m *Action) XXX_Size() int {
	return xxx_messageInfo_Action.Size(m)
}
func (m *Action) XXX_DiscardUnknown() {
	xxx_messageInfo_Action.DiscardUnknown(m)
}

var xxx_messageInfo_Action proto.InternalMessageInfo

func (m *Action) GetActionType() Action_ActionType {
	if m != nil {
		return m.ActionType
	}
	return Action_CUSTOM
}

func (m *Action) GetCustomAction() *CustomAction {
	if m != nil {
		return m.CustomAction
	}
	return nil
}

func (m *Action) GetShadow() bool {
	if m != nil {
		return m.Shadow
	}
	return false
}

type CustomAction struct {
	Name                 string         `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Regex                []string       `protobuf:"bytes,2,rep,name=regex,proto3" json:"regex,omitempty"`
	MaskChar             string         `protobuf:"bytes,3,opt,name=mask_char,json=maskChar,proto3" json:"mask_char,omitempty"`
	Percent              *_type.Percent `protobuf:"bytes,4,opt,name=percent,proto3" json:"percent,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *CustomAction) Reset()         { *m = CustomAction{} }
func (m *CustomAction) String() string { return proto.CompactTextString(m) }
func (*CustomAction) ProtoMessage()    {}
func (*CustomAction) Descriptor() ([]byte, []int) {
	return fileDescriptor_34ec831aa7b23456, []int{4}
}
func (m *CustomAction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CustomAction.Unmarshal(m, b)
}
func (m *CustomAction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CustomAction.Marshal(b, m, deterministic)
}
func (m *CustomAction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CustomAction.Merge(m, src)
}
func (m *CustomAction) XXX_Size() int {
	return xxx_messageInfo_CustomAction.Size(m)
}
func (m *CustomAction) XXX_DiscardUnknown() {
	xxx_messageInfo_CustomAction.DiscardUnknown(m)
}

var xxx_messageInfo_CustomAction proto.InternalMessageInfo

func (m *CustomAction) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CustomAction) GetRegex() []string {
	if m != nil {
		return m.Regex
	}
	return nil
}

func (m *CustomAction) GetMaskChar() string {
	if m != nil {
		return m.MaskChar
	}
	return ""
}

func (m *CustomAction) GetPercent() *_type.Percent {
	if m != nil {
		return m.Percent
	}
	return nil
}

func init() {
	proto.RegisterEnum("dlp.plugins.gloo.solo.io.Action_ActionType", Action_ActionType_name, Action_ActionType_value)
	proto.RegisterType((*Config)(nil), "dlp.plugins.gloo.solo.io.Config")
	proto.RegisterType((*FilterConfig)(nil), "dlp.plugins.gloo.solo.io.FilterConfig")
	proto.RegisterType((*DlpRule)(nil), "dlp.plugins.gloo.solo.io.DlpRule")
	proto.RegisterType((*Action)(nil), "dlp.plugins.gloo.solo.io.Action")
	proto.RegisterType((*CustomAction)(nil), "dlp.plugins.gloo.solo.io.CustomAction")
}

func init() {
	proto.RegisterFile("github.com/solo-io/gloo/projects/gloo/api/v1/enterprise/plugins/dlp/dlp.proto", fileDescriptor_34ec831aa7b23456)
}

var fileDescriptor_34ec831aa7b23456 = []byte{
	// 569 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x53, 0x4f, 0x6f, 0xd3, 0x4e,
	0x10, 0xfd, 0x39, 0x49, 0xf3, 0x67, 0x92, 0x5f, 0xb1, 0x96, 0x08, 0x59, 0x45, 0x42, 0x21, 0x48,
	0xa8, 0x12, 0xea, 0x5a, 0x94, 0x1b, 0x12, 0x48, 0xae, 0x6d, 0x50, 0x68, 0xdc, 0xa2, 0x75, 0x5a,
	0x21, 0x2e, 0x96, 0xeb, 0x2c, 0x8e, 0xa9, 0xe3, 0x5d, 0xad, 0x9d, 0x42, 0xef, 0x7c, 0x0d, 0xee,
	0x7c, 0x27, 0x6e, 0x7c, 0x12, 0xb4, 0xbb, 0x4e, 0x09, 0x87, 0x00, 0x3d, 0x44, 0x79, 0xf3, 0x66,
	0xe7, 0xed, 0xbe, 0x19, 0x0f, 0x04, 0x69, 0x56, 0x2d, 0x56, 0x17, 0x38, 0x61, 0x4b, 0xbb, 0x64,
	0x39, 0x3b, 0xc8, 0x98, 0x9d, 0xe6, 0x8c, 0xd9, 0x5c, 0xb0, 0x8f, 0x34, 0xa9, 0x4a, 0x1d, 0xc5,
	0x3c, 0xb3, 0xaf, 0x9e, 0xda, 0xb4, 0xa8, 0xa8, 0xe0, 0x22, 0x2b, 0xa9, 0xcd, 0xf3, 0x55, 0x9a,
	0x15, 0xa5, 0x3d, 0xcf, 0xb9, 0xfc, 0x61, 0x2e, 0x58, 0xc5, 0x90, 0xa5, 0xa0, 0x4e, 0x61, 0x59,
	0x89, 0xa5, 0x28, 0xce, 0xd8, 0xde, 0xe4, 0x56, 0x17, 0x25, 0x4c, 0x50, 0x7b, 0x19, 0x57, 0xc9,
	0x82, 0x8a, 0xf2, 0x06, 0xe8, 0x4b, 0xf6, 0x2c, 0x5a, 0x5c, 0xb1, 0x6b, 0xbb, 0xba, 0xe6, 0xd4,
	0xe6, 0x54, 0x24, 0xb4, 0xa8, 0xea, 0xcc, 0x30, 0x65, 0x29, 0x53, 0xd0, 0x96, 0x48, 0xb3, 0x63,
	0x0f, 0xda, 0x2e, 0x2b, 0x3e, 0x64, 0x29, 0x7a, 0x0e, 0x9d, 0x38, 0xa9, 0x32, 0x56, 0x94, 0x96,
	0x31, 0x6a, 0xee, 0xf7, 0x0f, 0x47, 0x78, 0xdb, 0x83, 0xb1, 0xa3, 0x0e, 0x92, 0x75, 0xc1, 0xf8,
	0x04, 0x06, 0xaf, 0xb2, 0xbc, 0xa2, 0xa2, 0xd6, 0x7a, 0x09, 0xbd, 0x79, 0xce, 0x23, 0xb1, 0xca,
	0xe9, 0x5a, 0xed, 0xe1, 0x76, 0x35, 0x2f, 0xe7, 0x64, 0x95, 0x53, 0xd2, 0x9d, 0x6b, 0x50, 0x8e,
	0xbf, 0x18, 0xd0, 0xa9, 0x59, 0xf4, 0x02, 0x3a, 0xb5, 0x47, 0xcb, 0x18, 0x19, 0xfb, 0xfd, 0xc3,
	0x47, 0x58, 0x76, 0x00, 0xdf, 0x18, 0xff, 0x4d, 0x2b, 0xd0, 0x2c, 0x59, 0xd7, 0x6c, 0xda, 0x6a,
	0xdc, 0xd6, 0xd6, 0xf7, 0x06, 0xb4, 0x35, 0x87, 0xa6, 0xd0, 0xd7, 0x6c, 0x24, 0x5b, 0xab, 0x5e,
	0xb2, 0x7b, 0xf8, 0xe4, 0x6f, 0x52, 0xf5, 0xdf, 0xec, 0x9a, 0x53, 0x02, 0xf1, 0x0d, 0x46, 0xc7,
	0xf0, 0x7f, 0xb2, 0x2a, 0x2b, 0xb6, 0x8c, 0x34, 0x69, 0x35, 0x94, 0xb3, 0xc7, 0xdb, 0xf5, 0x5c,
	0x75, 0xbc, 0x7e, 0xe0, 0x20, 0xd9, 0x88, 0xd0, 0x3d, 0x68, 0x97, 0x8b, 0x78, 0xce, 0x3e, 0x59,
	0xcd, 0x91, 0xb1, 0xdf, 0x25, 0x75, 0x34, 0xfe, 0x6a, 0x00, 0xfc, 0xba, 0x1f, 0x01, 0xb4, 0xdd,
	0xb3, 0x70, 0x76, 0x1a, 0x98, 0xff, 0xa1, 0x0e, 0x34, 0xc3, 0xf0, 0xc4, 0x34, 0xd0, 0x2e, 0x40,
	0xe0, 0x84, 0x33, 0x9f, 0xb8, 0x0e, 0xf1, 0xcc, 0x06, 0xea, 0x42, 0xeb, 0x7c, 0x12, 0x3a, 0x66,
	0x53, 0x22, 0x27, 0xf0, 0xdf, 0x99, 0x2d, 0x34, 0x80, 0xae, 0x37, 0x09, 0xdd, 0xd3, 0x73, 0x9f,
	0x98, 0x3b, 0xb2, 0xf4, 0x8d, 0x7b, 0x64, 0xb6, 0xd1, 0x1d, 0xe8, 0x7b, 0x93, 0x13, 0x9f, 0x84,
	0x91, 0x3b, 0x3d, 0x3b, 0x32, 0x3b, 0xc8, 0x82, 0xa1, 0x4b, 0x7c, 0x6f, 0x32, 0x8b, 0xa4, 0x58,
	0x34, 0x23, 0x8e, 0x7b, 0xec, 0x93, 0xd0, 0xec, 0xa2, 0x21, 0x98, 0xce, 0x74, 0x1a, 0x6d, 0x64,
	0x43, 0xb3, 0x27, 0x87, 0x3c, 0xd8, 0xb4, 0x85, 0x10, 0xb4, 0x8a, 0x78, 0xa9, 0x9b, 0xdb, 0x23,
	0x0a, 0xa3, 0x21, 0xec, 0x08, 0x9a, 0xd2, 0xcf, 0x6a, 0x78, 0x3d, 0xa2, 0x03, 0x74, 0x1f, 0x7a,
	0xcb, 0xb8, 0xbc, 0x8c, 0x92, 0x45, 0x2c, 0x94, 0xeb, 0x1e, 0xe9, 0x4a, 0xc2, 0x5d, 0xc4, 0x02,
	0x1d, 0x40, 0xa7, 0xfe, 0xf2, 0xad, 0x96, 0x6a, 0xeb, 0x5d, 0xac, 0x96, 0x02, 0xcb, 0xc9, 0xe1,
	0xb7, 0x3a, 0x45, 0xd6, 0x67, 0x8e, 0x82, 0x6f, 0x3f, 0x1e, 0x18, 0xef, 0x5f, 0xff, 0xdb, 0x0a,
	0xf2, 0xcb, 0xf4, 0xcf, 0xfb, 0x7e, 0xd1, 0x56, 0x7b, 0xf5, 0xec, 0x67, 0x00, 0x00, 0x00, 0xff,
	0xff, 0xa1, 0xca, 0xd8, 0xc3, 0x3d, 0x04, 0x00, 0x00,
}

func (this *Config) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Config)
	if !ok {
		that2, ok := that.(Config)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if len(this.Actions) != len(that1.Actions) {
		return false
	}
	for i := range this.Actions {
		if !this.Actions[i].Equal(that1.Actions[i]) {
			return false
		}
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}
func (this *FilterConfig) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*FilterConfig)
	if !ok {
		that2, ok := that.(FilterConfig)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if len(this.DlpRules) != len(that1.DlpRules) {
		return false
	}
	for i := range this.DlpRules {
		if !this.DlpRules[i].Equal(that1.DlpRules[i]) {
			return false
		}
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}
func (this *DlpRule) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*DlpRule)
	if !ok {
		that2, ok := that.(DlpRule)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.Matcher.Equal(that1.Matcher) {
		return false
	}
	if len(this.Actions) != len(that1.Actions) {
		return false
	}
	for i := range this.Actions {
		if !this.Actions[i].Equal(that1.Actions[i]) {
			return false
		}
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}
func (this *Action) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Action)
	if !ok {
		that2, ok := that.(Action)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.ActionType != that1.ActionType {
		return false
	}
	if !this.CustomAction.Equal(that1.CustomAction) {
		return false
	}
	if this.Shadow != that1.Shadow {
		return false
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}
func (this *CustomAction) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*CustomAction)
	if !ok {
		that2, ok := that.(CustomAction)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Name != that1.Name {
		return false
	}
	if len(this.Regex) != len(that1.Regex) {
		return false
	}
	for i := range this.Regex {
		if this.Regex[i] != that1.Regex[i] {
			return false
		}
	}
	if this.MaskChar != that1.MaskChar {
		return false
	}
	if !this.Percent.Equal(that1.Percent) {
		return false
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}
