// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: github.com/solo-io/gloo/projects/gloo/api/v1/enterprise/options/failover/failover.proto

package failover

import (
	bytes "bytes"
	fmt "fmt"
	math "math"

	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	types "github.com/gogo/protobuf/types"
	v3 "github.com/solo-io/gloo/projects/gloo/pkg/api/external/envoy/config/core/v3"
	core1 "github.com/solo-io/gloo/projects/gloo/pkg/api/v1/core"
	_ "github.com/solo-io/protoc-gen-ext/extproto"
	core "github.com/solo-io/solo-kit/pkg/api/v1/resources/core"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

//
//
//Failover configuration for an upstream.
//
//Failover allows for optional fallback endpoints in the case that the primary set of endpoints is deemed
//unhealthy. As failover requires knowledge of the health of each set of endpoints, active or passive
//health checks must be configured on an upstream using failover in order for it to work properly.
//
//Failover closely resembles the Envoy config which this is translated to, with one notable exception.
//The priorities are not defined on the `LocalityLbEndpoints` but rather inferred from the list of
//`PrioritizedLocality`. More information on envoy prioritization can be found
//[here](https://www.envoyproxy.io/docs/envoy/v1.14.1/intro/arch_overview/upstream/load_balancing/priority#arch-overview-load-balancing-priority-levels).
//In practice this means that the priority of a given set of `LocalityLbEndpoints` is determined by it's index in
//the list, first being `0` through `n-1`.
//
type Failover struct {
	// Identifies location of where the parent upstream hosts run.
	Locality *v3.Locality `protobuf:"bytes,1,opt,name=locality,proto3" json:"locality,omitempty"`
	// PrioritizedLocality is an implicitly prioritized list of lists of `LocalityLbEndpoints`. The priority of each
	// list of `LocalityLbEndpoints` is determined by it's index in the list.
	PrioritizedLocalities []*Failover_PrioritizedLocality `protobuf:"bytes,2,rep,name=prioritized_localities,json=prioritizedLocalities,proto3" json:"prioritized_localities,omitempty"`
	XXX_NoUnkeyedLiteral  struct{}                        `json:"-"`
	XXX_unrecognized      []byte                          `json:"-"`
	XXX_sizecache         int32                           `json:"-"`
}

func (m *Failover) Reset()         { *m = Failover{} }
func (m *Failover) String() string { return proto.CompactTextString(m) }
func (*Failover) ProtoMessage()    {}
func (*Failover) Descriptor() ([]byte, []int) {
	return fileDescriptor_d8087bcbe8320ae9, []int{0}
}
func (m *Failover) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Failover.Unmarshal(m, b)
}
func (m *Failover) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Failover.Marshal(b, m, deterministic)
}
func (m *Failover) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Failover.Merge(m, src)
}
func (m *Failover) XXX_Size() int {
	return xxx_messageInfo_Failover.Size(m)
}
func (m *Failover) XXX_DiscardUnknown() {
	xxx_messageInfo_Failover.DiscardUnknown(m)
}

var xxx_messageInfo_Failover proto.InternalMessageInfo

func (m *Failover) GetLocality() *v3.Locality {
	if m != nil {
		return m.Locality
	}
	return nil
}

func (m *Failover) GetPrioritizedLocalities() []*Failover_PrioritizedLocality {
	if m != nil {
		return m.PrioritizedLocalities
	}
	return nil
}

type Failover_PrioritizedLocality struct {
	LocalityEndpoints []*LocalityLbEndpoints `protobuf:"bytes,1,rep,name=locality_endpoints,json=localityEndpoints,proto3" json:"locality_endpoints,omitempty"`
	// A list of references to kubernetes services to be used as endpoints for this priority.
	// As each kubernetes service must be located in the current cluster, the locality will be
	// left empty, and all endpoints from these services will be given the same load_balancing_weight.
	KubeServices         []*core.ResourceRef `protobuf:"bytes,2,rep,name=kube_services,json=kubeServices,proto3" json:"kube_services,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *Failover_PrioritizedLocality) Reset()         { *m = Failover_PrioritizedLocality{} }
func (m *Failover_PrioritizedLocality) String() string { return proto.CompactTextString(m) }
func (*Failover_PrioritizedLocality) ProtoMessage()    {}
func (*Failover_PrioritizedLocality) Descriptor() ([]byte, []int) {
	return fileDescriptor_d8087bcbe8320ae9, []int{0, 0}
}
func (m *Failover_PrioritizedLocality) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Failover_PrioritizedLocality.Unmarshal(m, b)
}
func (m *Failover_PrioritizedLocality) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Failover_PrioritizedLocality.Marshal(b, m, deterministic)
}
func (m *Failover_PrioritizedLocality) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Failover_PrioritizedLocality.Merge(m, src)
}
func (m *Failover_PrioritizedLocality) XXX_Size() int {
	return xxx_messageInfo_Failover_PrioritizedLocality.Size(m)
}
func (m *Failover_PrioritizedLocality) XXX_DiscardUnknown() {
	xxx_messageInfo_Failover_PrioritizedLocality.DiscardUnknown(m)
}

var xxx_messageInfo_Failover_PrioritizedLocality proto.InternalMessageInfo

func (m *Failover_PrioritizedLocality) GetLocalityEndpoints() []*LocalityLbEndpoints {
	if m != nil {
		return m.LocalityEndpoints
	}
	return nil
}

func (m *Failover_PrioritizedLocality) GetKubeServices() []*core.ResourceRef {
	if m != nil {
		return m.KubeServices
	}
	return nil
}

// Upstream host identifier.
type Endpoint struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Endpoint) Reset()         { *m = Endpoint{} }
func (m *Endpoint) String() string { return proto.CompactTextString(m) }
func (*Endpoint) ProtoMessage()    {}
func (*Endpoint) Descriptor() ([]byte, []int) {
	return fileDescriptor_d8087bcbe8320ae9, []int{1}
}
func (m *Endpoint) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Endpoint.Unmarshal(m, b)
}
func (m *Endpoint) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Endpoint.Marshal(b, m, deterministic)
}
func (m *Endpoint) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Endpoint.Merge(m, src)
}
func (m *Endpoint) XXX_Size() int {
	return xxx_messageInfo_Endpoint.Size(m)
}
func (m *Endpoint) XXX_DiscardUnknown() {
	xxx_messageInfo_Endpoint.DiscardUnknown(m)
}

var xxx_messageInfo_Endpoint proto.InternalMessageInfo

// An Endpoint that Envoy can route traffic to.
// [#next-free-field: 6]
type LbEndpoint struct {
	// Address (hostname or IP)
	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	// Port the instance is listening on
	Port uint32 `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	// The optional health check configuration is used as configuration for the
	// health checker to contact the health checked host.
	//
	// .. attention::
	//
	//   This takes into effect only for upstream clusters with
	//   :ref:`active health checking <arch_overview_health_checking>` enabled.
	HealthCheckConfig *LbEndpoint_HealthCheckConfig `protobuf:"bytes,3,opt,name=health_check_config,json=healthCheckConfig,proto3" json:"health_check_config,omitempty"`
	UpstreamSslConfig *core1.UpstreamSslConfig      `protobuf:"bytes,4,opt,name=upstream_ssl_config,json=upstreamSslConfig,proto3" json:"upstream_ssl_config,omitempty"`
	// The optional load balancing weight of the upstream host; at least 1.
	// Envoy uses the load balancing weight in some of the built in load
	// balancers. The load balancing weight for an endpoint is divided by the sum
	// of the weights of all endpoints in the endpoint's locality to produce a
	// percentage of traffic for the endpoint. This percentage is then further
	// weighted by the endpoint's locality's load balancing weight from
	// LocalityLbEndpoints. If unspecified, each host is presumed to have equal
	// weight in a locality.
	LoadBalancingWeight  *types.UInt32Value `protobuf:"bytes,5,opt,name=load_balancing_weight,json=loadBalancingWeight,proto3" json:"load_balancing_weight,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *LbEndpoint) Reset()         { *m = LbEndpoint{} }
func (m *LbEndpoint) String() string { return proto.CompactTextString(m) }
func (*LbEndpoint) ProtoMessage()    {}
func (*LbEndpoint) Descriptor() ([]byte, []int) {
	return fileDescriptor_d8087bcbe8320ae9, []int{2}
}
func (m *LbEndpoint) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LbEndpoint.Unmarshal(m, b)
}
func (m *LbEndpoint) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LbEndpoint.Marshal(b, m, deterministic)
}
func (m *LbEndpoint) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LbEndpoint.Merge(m, src)
}
func (m *LbEndpoint) XXX_Size() int {
	return xxx_messageInfo_LbEndpoint.Size(m)
}
func (m *LbEndpoint) XXX_DiscardUnknown() {
	xxx_messageInfo_LbEndpoint.DiscardUnknown(m)
}

var xxx_messageInfo_LbEndpoint proto.InternalMessageInfo

func (m *LbEndpoint) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *LbEndpoint) GetPort() uint32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *LbEndpoint) GetHealthCheckConfig() *LbEndpoint_HealthCheckConfig {
	if m != nil {
		return m.HealthCheckConfig
	}
	return nil
}

func (m *LbEndpoint) GetUpstreamSslConfig() *core1.UpstreamSslConfig {
	if m != nil {
		return m.UpstreamSslConfig
	}
	return nil
}

func (m *LbEndpoint) GetLoadBalancingWeight() *types.UInt32Value {
	if m != nil {
		return m.LoadBalancingWeight
	}
	return nil
}

// The optional health check configuration.
type LbEndpoint_HealthCheckConfig struct {
	// Optional alternative health check port value.
	//
	// By default the health check address port of an upstream host is the same
	// as the host's serving address port. This provides an alternative health
	// check port. Setting this with a non-zero value allows an upstream host
	// to have different health check address port.
	PortValue uint32 `protobuf:"varint,1,opt,name=port_value,json=portValue,proto3" json:"port_value,omitempty"`
	// By default, the host header for L7 health checks is controlled by cluster level configuration
	// (see: :ref:`host <envoy_api_field_config.core.v3.HealthCheck.HttpHealthCheck.host>` and
	// :ref:`authority <envoy_api_field_config.core.v3.HealthCheck.GrpcHealthCheck.authority>`). Setting this
	// to a non-empty value allows overriding the cluster level configuration for a specific
	// endpoint.
	Hostname             string   `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LbEndpoint_HealthCheckConfig) Reset()         { *m = LbEndpoint_HealthCheckConfig{} }
func (m *LbEndpoint_HealthCheckConfig) String() string { return proto.CompactTextString(m) }
func (*LbEndpoint_HealthCheckConfig) ProtoMessage()    {}
func (*LbEndpoint_HealthCheckConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_d8087bcbe8320ae9, []int{2, 0}
}
func (m *LbEndpoint_HealthCheckConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LbEndpoint_HealthCheckConfig.Unmarshal(m, b)
}
func (m *LbEndpoint_HealthCheckConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LbEndpoint_HealthCheckConfig.Marshal(b, m, deterministic)
}
func (m *LbEndpoint_HealthCheckConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LbEndpoint_HealthCheckConfig.Merge(m, src)
}
func (m *LbEndpoint_HealthCheckConfig) XXX_Size() int {
	return xxx_messageInfo_LbEndpoint_HealthCheckConfig.Size(m)
}
func (m *LbEndpoint_HealthCheckConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_LbEndpoint_HealthCheckConfig.DiscardUnknown(m)
}

var xxx_messageInfo_LbEndpoint_HealthCheckConfig proto.InternalMessageInfo

func (m *LbEndpoint_HealthCheckConfig) GetPortValue() uint32 {
	if m != nil {
		return m.PortValue
	}
	return 0
}

func (m *LbEndpoint_HealthCheckConfig) GetHostname() string {
	if m != nil {
		return m.Hostname
	}
	return ""
}

// A group of endpoints belonging to a Locality.
// One can have multiple LocalityLbEndpoints for a locality, but this is
// generally only done if the different groups need to have different load
// balancing weights or different priorities.
type LocalityLbEndpoints struct {
	// Identifies location of where the upstream hosts run.
	Locality *v3.Locality `protobuf:"bytes,1,opt,name=locality,proto3" json:"locality,omitempty"`
	// The group of endpoints belonging to the locality specified.
	LbEndpoints []*LbEndpoint `protobuf:"bytes,2,rep,name=lb_endpoints,json=lbEndpoints,proto3" json:"lb_endpoints,omitempty"`
	// Optional: Per priority/region/zone/sub_zone weight; at least 1. The load
	// balancing weight for a locality is divided by the sum of the weights of all
	// localities  at the same priority level to produce the effective percentage
	// of traffic for the locality.
	//
	// Locality weights are only considered when :ref:`locality weighted load
	// balancing <arch_overview_load_balancing_locality_weighted_lb>` is
	// configured. These weights are ignored otherwise. If no weights are
	// specified when locality weighted load balancing is enabled, the locality is
	// assigned no load.
	LoadBalancingWeight  *types.UInt32Value `protobuf:"bytes,3,opt,name=load_balancing_weight,json=loadBalancingWeight,proto3" json:"load_balancing_weight,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *LocalityLbEndpoints) Reset()         { *m = LocalityLbEndpoints{} }
func (m *LocalityLbEndpoints) String() string { return proto.CompactTextString(m) }
func (*LocalityLbEndpoints) ProtoMessage()    {}
func (*LocalityLbEndpoints) Descriptor() ([]byte, []int) {
	return fileDescriptor_d8087bcbe8320ae9, []int{3}
}
func (m *LocalityLbEndpoints) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LocalityLbEndpoints.Unmarshal(m, b)
}
func (m *LocalityLbEndpoints) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LocalityLbEndpoints.Marshal(b, m, deterministic)
}
func (m *LocalityLbEndpoints) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LocalityLbEndpoints.Merge(m, src)
}
func (m *LocalityLbEndpoints) XXX_Size() int {
	return xxx_messageInfo_LocalityLbEndpoints.Size(m)
}
func (m *LocalityLbEndpoints) XXX_DiscardUnknown() {
	xxx_messageInfo_LocalityLbEndpoints.DiscardUnknown(m)
}

var xxx_messageInfo_LocalityLbEndpoints proto.InternalMessageInfo

func (m *LocalityLbEndpoints) GetLocality() *v3.Locality {
	if m != nil {
		return m.Locality
	}
	return nil
}

func (m *LocalityLbEndpoints) GetLbEndpoints() []*LbEndpoint {
	if m != nil {
		return m.LbEndpoints
	}
	return nil
}

func (m *LocalityLbEndpoints) GetLoadBalancingWeight() *types.UInt32Value {
	if m != nil {
		return m.LoadBalancingWeight
	}
	return nil
}

func init() {
	proto.RegisterType((*Failover)(nil), "failover.options.gloo.solo.io.Failover")
	proto.RegisterType((*Failover_PrioritizedLocality)(nil), "failover.options.gloo.solo.io.Failover.PrioritizedLocality")
	proto.RegisterType((*Endpoint)(nil), "failover.options.gloo.solo.io.Endpoint")
	proto.RegisterType((*LbEndpoint)(nil), "failover.options.gloo.solo.io.LbEndpoint")
	proto.RegisterType((*LbEndpoint_HealthCheckConfig)(nil), "failover.options.gloo.solo.io.LbEndpoint.HealthCheckConfig")
	proto.RegisterType((*LocalityLbEndpoints)(nil), "failover.options.gloo.solo.io.LocalityLbEndpoints")
}

func init() {
	proto.RegisterFile("github.com/solo-io/gloo/projects/gloo/api/v1/enterprise/options/failover/failover.proto", fileDescriptor_d8087bcbe8320ae9)
}

var fileDescriptor_d8087bcbe8320ae9 = []byte{
	// 628 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x54, 0xcb, 0x4e, 0xdc, 0x4a,
	0x10, 0x95, 0x19, 0xee, 0xbd, 0x43, 0x03, 0x0b, 0x7a, 0x2e, 0x91, 0x19, 0x05, 0x82, 0x46, 0x59,
	0x4c, 0x16, 0x69, 0x2b, 0x33, 0xbb, 0x44, 0xca, 0x02, 0x94, 0x28, 0x91, 0x46, 0x11, 0x32, 0x01,
	0xa4, 0x6c, 0xac, 0xb6, 0xa7, 0xc6, 0xee, 0x4c, 0xe3, 0xb2, 0xba, 0xdb, 0x06, 0xf2, 0x33, 0xd9,
	0xe6, 0x13, 0xf8, 0x9e, 0xfc, 0x41, 0x16, 0xec, 0x23, 0xb7, 0x1f, 0x10, 0x1e, 0x01, 0x25, 0xbb,
	0xae, 0xd3, 0xa7, 0x4e, 0x55, 0x9d, 0x7e, 0x90, 0xa3, 0x58, 0x98, 0x24, 0x0f, 0x59, 0x84, 0xc7,
	0x9e, 0x46, 0x89, 0xcf, 0x05, 0x7a, 0xb1, 0x44, 0xf4, 0x32, 0x85, 0x9f, 0x21, 0x32, 0xba, 0x8a,
	0x78, 0x26, 0xbc, 0xe2, 0x85, 0x07, 0xa9, 0x01, 0x95, 0x29, 0xa1, 0xc1, 0xc3, 0xcc, 0x08, 0x4c,
	0xb5, 0x37, 0xe3, 0x42, 0x62, 0x01, 0xaa, 0x5d, 0xb0, 0x4c, 0xa1, 0x41, 0xba, 0xd9, 0xc6, 0x35,
	0x93, 0x95, 0x42, 0xac, 0xac, 0xc1, 0x04, 0xf6, 0xff, 0x8f, 0x31, 0x46, 0xcb, 0xf4, 0xca, 0x55,
	0x95, 0xd4, 0xa7, 0x70, 0x6a, 0x2a, 0x10, 0x4e, 0x4d, 0x8d, 0x6d, 0xc5, 0x88, 0xb1, 0x04, 0xcf,
	0x46, 0x61, 0x3e, 0xf3, 0x4e, 0x14, 0xcf, 0x32, 0x50, 0xba, 0xde, 0x1f, 0xde, 0xdd, 0x6e, 0x84,
	0x0a, 0x3c, 0xad, 0x65, 0xcd, 0xdc, 0xb0, 0x03, 0xce, 0x85, 0x69, 0xf6, 0x15, 0xcc, 0xea, 0xad,
	0x27, 0x90, 0x16, 0x78, 0xe6, 0x45, 0x98, 0xce, 0x44, 0x5c, 0xe5, 0x15, 0x63, 0x2f, 0xe4, 0x1a,
	0x2a, 0xc2, 0xe0, 0x62, 0x81, 0x74, 0xdf, 0xd6, 0x13, 0xd1, 0x97, 0xa4, 0x2b, 0x31, 0xe2, 0x52,
	0x98, 0x33, 0xd7, 0xd9, 0x76, 0x86, 0xcb, 0xa3, 0x2d, 0x66, 0x05, 0x58, 0x25, 0xc0, 0x4a, 0x01,
	0x56, 0x8c, 0xd9, 0xa4, 0x66, 0xf9, 0x2d, 0x9f, 0x2a, 0xf2, 0x28, 0x53, 0x02, 0x95, 0x30, 0xe2,
	0x0b, 0x4c, 0x83, 0x1a, 0x17, 0xa0, 0xdd, 0x85, 0xed, 0xce, 0x70, 0x79, 0xf4, 0x8a, 0xfd, 0xd6,
	0x38, 0xd6, 0x34, 0xc1, 0xf6, 0x2e, 0x55, 0xda, 0x32, 0xeb, 0xd9, 0x0d, 0x50, 0x80, 0xee, 0x9f,
	0x3b, 0xa4, 0x77, 0x0b, 0x9d, 0x72, 0x42, 0x9b, 0xbe, 0x02, 0x48, 0xa7, 0x19, 0x8a, 0xd4, 0x68,
	0xd7, 0xb1, 0x7d, 0x8c, 0xee, 0xe9, 0xa3, 0x11, 0x99, 0x84, 0x6f, 0x9a, 0x4c, 0x7f, 0xad, 0x51,
	0x6b, 0x21, 0xfa, 0x9a, 0xac, 0xce, 0xf3, 0x10, 0x02, 0x0d, 0xaa, 0x10, 0x51, 0x3b, 0xe5, 0x46,
	0x65, 0x51, 0x23, 0xe6, 0x83, 0xc6, 0x5c, 0x45, 0xe0, 0xc3, 0xcc, 0x5f, 0x29, 0xf9, 0xfb, 0x35,
	0x7d, 0x40, 0x48, 0xb7, 0x11, 0x1b, 0x7c, 0xed, 0x10, 0x72, 0x59, 0x8e, 0xba, 0xe4, 0x3f, 0x3e,
	0x9d, 0x2a, 0xd0, 0xda, 0x1e, 0xc2, 0x92, 0xdf, 0x84, 0x94, 0x92, 0xc5, 0x0c, 0x95, 0x71, 0x17,
	0xb6, 0x9d, 0xe1, 0xaa, 0x6f, 0xd7, 0x74, 0x4e, 0x7a, 0x09, 0x70, 0x69, 0x92, 0x20, 0x4a, 0x20,
	0x9a, 0x07, 0xd5, 0x49, 0xb9, 0x1d, 0x7b, 0x7c, 0xf7, 0x99, 0x7e, 0x59, 0x95, 0xbd, 0xb3, 0x22,
	0xbb, 0xa5, 0xc6, 0xae, 0x95, 0xf0, 0xd7, 0x92, 0xeb, 0x10, 0xfd, 0x48, 0x7a, 0x79, 0xa6, 0x8d,
	0x02, 0x7e, 0x1c, 0x68, 0x2d, 0x9b, 0x62, 0x8b, 0xb6, 0xd8, 0xd3, 0x6a, 0xf6, 0x5f, 0x0a, 0x1c,
	0xd4, 0xec, 0x7d, 0x2d, 0x1b, 0xd5, 0xfc, 0x3a, 0x44, 0xf7, 0xc8, 0xba, 0x44, 0x3e, 0x0d, 0x42,
	0x2e, 0x79, 0x1a, 0x89, 0x34, 0x0e, 0x4e, 0x40, 0xc4, 0x89, 0x71, 0xff, 0xb1, 0xba, 0x8f, 0x59,
	0xf5, 0x52, 0x58, 0xf3, 0x52, 0xd8, 0xc1, 0xfb, 0xd4, 0x8c, 0x47, 0x87, 0x5c, 0xe6, 0xe0, 0xf7,
	0xca, 0xd4, 0x9d, 0x26, 0xf3, 0xc8, 0x26, 0xf6, 0x3f, 0x90, 0xb5, 0x1b, 0xf3, 0xd0, 0x4d, 0x42,
	0x4a, 0xc7, 0x82, 0xa2, 0xcc, 0xb3, 0xd6, 0xae, 0xfa, 0x4b, 0x25, 0x62, 0x85, 0x68, 0x9f, 0x74,
	0x13, 0xd4, 0x26, 0xe5, 0xc7, 0x60, 0x0d, 0x5e, 0xf2, 0xdb, 0x78, 0xf0, 0xc3, 0x21, 0xbd, 0x5b,
	0x2e, 0xc6, 0x5f, 0x3d, 0x98, 0x09, 0x59, 0x91, 0xe1, 0x95, 0xeb, 0x59, 0x5d, 0xa0, 0x67, 0x0f,
	0x3e, 0x31, 0x7f, 0x59, 0x5e, 0xe9, 0xe4, 0x4e, 0x0f, 0x3b, 0x7f, 0xe8, 0xe1, 0xce, 0xe1, 0xf9,
	0xc5, 0xa2, 0xf3, 0xed, 0xfb, 0x96, 0xf3, 0x69, 0xf2, 0xb0, 0xbf, 0x34, 0x9b, 0xc7, 0x0f, 0xf8,
	0x4f, 0xc3, 0x7f, 0x6d, 0x0b, 0xe3, 0x9f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x69, 0x8e, 0xee, 0xf3,
	0xa2, 0x05, 0x00, 0x00,
}

func (this *Failover) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Failover)
	if !ok {
		that2, ok := that.(Failover)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.Locality.Equal(that1.Locality) {
		return false
	}
	if len(this.PrioritizedLocalities) != len(that1.PrioritizedLocalities) {
		return false
	}
	for i := range this.PrioritizedLocalities {
		if !this.PrioritizedLocalities[i].Equal(that1.PrioritizedLocalities[i]) {
			return false
		}
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}
func (this *Failover_PrioritizedLocality) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Failover_PrioritizedLocality)
	if !ok {
		that2, ok := that.(Failover_PrioritizedLocality)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if len(this.LocalityEndpoints) != len(that1.LocalityEndpoints) {
		return false
	}
	for i := range this.LocalityEndpoints {
		if !this.LocalityEndpoints[i].Equal(that1.LocalityEndpoints[i]) {
			return false
		}
	}
	if len(this.KubeServices) != len(that1.KubeServices) {
		return false
	}
	for i := range this.KubeServices {
		if !this.KubeServices[i].Equal(that1.KubeServices[i]) {
			return false
		}
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}
func (this *Endpoint) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Endpoint)
	if !ok {
		that2, ok := that.(Endpoint)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}
func (this *LbEndpoint) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*LbEndpoint)
	if !ok {
		that2, ok := that.(LbEndpoint)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Address != that1.Address {
		return false
	}
	if this.Port != that1.Port {
		return false
	}
	if !this.HealthCheckConfig.Equal(that1.HealthCheckConfig) {
		return false
	}
	if !this.UpstreamSslConfig.Equal(that1.UpstreamSslConfig) {
		return false
	}
	if !this.LoadBalancingWeight.Equal(that1.LoadBalancingWeight) {
		return false
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}
func (this *LbEndpoint_HealthCheckConfig) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*LbEndpoint_HealthCheckConfig)
	if !ok {
		that2, ok := that.(LbEndpoint_HealthCheckConfig)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.PortValue != that1.PortValue {
		return false
	}
	if this.Hostname != that1.Hostname {
		return false
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}
func (this *LocalityLbEndpoints) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*LocalityLbEndpoints)
	if !ok {
		that2, ok := that.(LocalityLbEndpoints)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.Locality.Equal(that1.Locality) {
		return false
	}
	if len(this.LbEndpoints) != len(that1.LbEndpoints) {
		return false
	}
	for i := range this.LbEndpoints {
		if !this.LbEndpoints[i].Equal(that1.LbEndpoints[i]) {
			return false
		}
	}
	if !this.LoadBalancingWeight.Equal(that1.LoadBalancingWeight) {
		return false
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}
